### ISSUE TITLE
Snow Dungeons generate in Badlands Biome

### ISSUE THREAD

**Issue by loganobrien** [TelepathicGrunt/RepurposedStructures-Fabric#1]
Hello

I'm using:
- fabric-loader-0.8.9+build.203-1.16.1
- repurposed_structures-1.16.1-1.0.0
- world seed: -932399906999827554

I saw that snow dungeons are generated in badlands biome:

![2020-07-03_11.07.49](http://mc.swissplay.net/data/img/screenshots/2020-07-03_11.07.49.png)

![2020-07-03_11.07.49](http://mc.swissplay.net/data/img/screenshots/2020-07-03_11.08.20.png)

![2020-07-03_11.07.49](http://mc.swissplay.net/data/img/screenshots/2020-07-03_11.08.47.png)

Is this by purpose? Looks kind of special/wrong to me, but please correct me if not.

Regards

**Comment by TelepathicGrunt** [comment]
What in the world... that that ain’t right lol. Is any other dungeon misplaced as well?

**Comment by loganobrien** [comment]
Not as far as I checked.

The mineshaft in the end dimension generate in the void (same seed):

![2020-07-03_11.51.24.png](http://mc.swissplay.net/data/img/screenshots/2020-07-03_11.51.24.png)

Is this also a "bug"? If yes, I can create an other issue for this. I guess it's quite hard to force them spawning only inside islands. I did not tweak the config files.

**Comment by TelepathicGrunt** [comment]
It’s center room should be starting in a non-void biome but the rest of it can go outward into the void. But that pic shows it completely in the void which isn’t right. I’ll start investigating more when I can.
Thank you for letting me know!

**Comment by TelepathicGrunt** [comment]
v1.0.1 is now out with the bug fix! Enjoy and let me know if any other issues arise! :)
