### ISSUE TITLE
Wells causing crash

### ISSUE THREAD

**Issue by connorgoober** [TelepathicGrunt/RepurposedStructures-Fabric#10]
Sometimes when im exploring in the nether ill get a crash. Apparently its something to do with the wells.
[crash-2020-07-17_00.40.14-server.txt](https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/files/4936406/crash-2020-07-17_00.40.14-server.txt)
[crash-2020-07-14_19.29.51-server.txt](https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/files/4936407/crash-2020-07-14_19.29.51-server.txt)

**Comment by TelepathicGrunt** [comment]
The line throwing null is this:
`blockState.isOf(world.getBiome(mutable).getSurfaceConfig().getTopMaterial().getBlock()))`

Seems like someone make a biome with no block in the surface builder or has no surface builder? What?

Can you describe which mod adds nether biomes? I see better nether so I'll test with that one first and see if it's their nether biomes

**Comment by TelepathicGrunt** [comment]
I can't seem to recreate the crash. I don't think it's better nether. Can you download and try this test jar? When it crashes, please give me the entire latest.log file and it should tell us which mod's biome is crash the well and I'll know what to check for to keep the well from crashing in the future!
[repurposed_structures-1.2.1b.zip](https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/files/4937512/repurposed_structures-1.2.1b.zip)

**Comment by connorgoober** [comment]
[crash-2020-07-17_04.51.37-server.txt](https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/files/4937581/crash-2020-07-17_04.51.37-server.txt)
[latest.log](https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/files/4937583/latest.log)
Crash report and the log.

**Comment by TelepathicGrunt** [comment]
Yeah it's Cinderscapes. Their AshyShoalsBiome uses a EmptySurfaceConfig which makes the .getBlock() crash as that surfaceconfig holds no blocks. This is literally the first and only mod I have ever seen that uses EmptySurfaceConfig lol.

I'll let them know this will cause crashes with lots of mods that checks for biome's top block as no one will expect .getTopMaterial() to return null. 1.2.1 will have some extra checks to prevent a crash against this. I'll let you know when it is finished

**Comment by TelepathicGrunt** [comment]
1.2.1 is now approved on curseforge and should prevent the crash from happening now. Thank you for letting me know about the crash!
https://www.curseforge.com/minecraft/mc-mods/repurposed-structures-fabric/files/3007240

I also am letting Cinderscapes know that returning null for a surfacebuilderconfig is a bad idea for mod compat and makes it harder for some mods to know what the biome's top block really is
