### ISSUE TITLE
Non-RP Advancements Inaccessible 

### ISSUE THREAD

**Issue by CatastropheBlack** [TelepathicGrunt/RepurposedStructures-Fabric#110]
Repurposed Structures appears to make all other advancements invisible/inaccessible.

![image](https://user-images.githubusercontent.com/33291018/116573993-ec8a0980-a8d2-11eb-8535-36bb2a5eaba2.png)

Minecraft v1.16.5
Fabric v0.11.3
Fabric API v0.33.1+1.16
Cloth Config API v4.11.19
Repurposed Structures v1.16.5-1.10.4-fabric

**Comment by TelepathicGrunt** [comment]
actually, this is vanilla behavior where you havent actually triggered another advancement yet. Try crafting a crafting table or something and the vanilla advancement screen will show up. The reason i know about this is someone reported this a while ago and after experimenting, we realized it's just how vanilla advancements works when you have no triggered advancements while i have repurposed structure's advancements show up right away
