### ISSUE TITLE
Crash in Jungle Village (Skin Index Crash)

### ISSUE THREAD

**Issue by PalgamingHD** [TelepathicGrunt/RepurposedStructures-Fabric#116]
https://pastebin.com/FRVJE9m7

And yes, I saw someone else reporting something similar. The mod I believe that this is a conflict with this mod:
https://www.curseforge.com/minecraft/mc-mods/npc-variety-port

**Comment by TelepathicGrunt** [comment]
Just fyi, if it's the same crash, you can reply to the other thread. But thank you for finding the mod! I'll test with it to see if it is the culprit. 

other issue report to link it to here: https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/issues/114

**Comment by PalgamingHD** [comment]
Alright sorry about that I wasn't 100%

**Comment by TelepathicGrunt** [comment]
No worries, I got in contact with the dev so hopefully a fix will come out soon!

**Comment by TelepathicGrunt** [comment]
Annnd they just released an update. Problem should be resolved now when you update their mod!
