### ISSUE TITLE
Blame report

### ISSUE THREAD

**Issue by srnyx** [TelepathicGrunt/RepurposedStructures-Fabric#117]
https://paste.srnyx.xyz/cicorulama.kotlin

**Comment by TelepathicGrunt** [comment]
What version of repurposed structures are you using? Do you have any datapack on that modifies repurposed structures? I ask cause right now, the warped outpost's template pool does not refer to the old tower_glowing name and uses tower_age on latest version

**Comment by srnyx** [comment]
> What version of repurposed structures are you using?

1.10.5

> Do you have any datapack on that modifies repurposed structures?

No

**Comment by TelepathicGrunt** [comment]
I just checked, nowhere do i have tower_glowing mentioned anymore. Thus, the issue cannot be coming from my mod. 
https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/search?q=tower_glowing

Only thing I can think of are other mods or datapacks referring to the old name of my warped outpost tower piece. Is there no other info in the log? Is it happening frequently?

**Comment by srnyx** [comment]
Is there no other info in the log?

Here is my full latest.log: https://paste.srnyx.xyz/asiturijaj.sql

> Is it happening frequently?

Since it's a Blame report, no

**Comment by TelepathicGrunt** [comment]
Weird. If you have some time to test, can you do `/locate repurposed_structures:outpost_warped` and teleport to a few warped outposts? If you can find these two warped outpost tower variants (one has shroomlight and the other does), then that means both tower variants are spawning just fine and you can ignore this blame report.
![image](https://user-images.githubusercontent.com/40846040/119731548-13d9e500-be45-11eb-823e-62b5c9f5d120.png)
![image](https://user-images.githubusercontent.com/40846040/119731608-26541e80-be45-11eb-89f1-f6672b83399b.png)

I'm not sure who is trying to spawn my warped outpost piece with the old name but I'll look into seeing if I can make Blame try a bit harder to find where the piece is being called from. But if both pieces are spawning in your world, then my mod is indeed working perfectly find and your world isn't missing any pieces.

**Comment by srnyx** [comment]
> can you do `/locate repurposed_structures:outpost_warped` and teleport to a few warped outposts? If you can find these two warped outpost tower variants (one has shroomlight and the other does), then that means both tower variants are spawning just fine and you can ignore this blame report.

Yep, found both of them, will ignore the report.
Thank you!
