### ISSUE TITLE
Structure Names

### ISSUE THREAD

**Issue by SlimeBoi2006** [TelepathicGrunt/RepurposedStructures-Fabric#122]
Hello, I recently removed Repurposed structure from my server due to the server updating to 1.17. I am trying to clean out all the structure files put in by the mod. Is there any way I can get a list of these structure names. I will include an example of what I mean.
![image](https://user-images.githubusercontent.com/84562128/123499322-bb843780-d5ea-11eb-91ce-39eed69b8038.png)

**Comment by TelepathicGrunt** [comment]
As long as you have Fabric API still on, the spam you see in the logs is just logspam. Your world is ok and safe to use. if you removed fabric api as well, then your only hope is to try the script a guy linked to in the comment section here: https://bugs.mojang.com/browse/MC-194811

Make a backup of your world before you try and use that. Hope this helps!

**Comment by SlimeBoi2006** [comment]
I am pretty sure that feature is not part of 1.17 fabric API

**Comment by SlimeBoi2006** [comment]
It is ok to use but it is really annoying when my server shuts down and I have no clue why because the entire console is filled with unknown structure messages.

**Comment by SlimeBoi2006** [comment]
Yes, I am doing the script right now, and that why I need the structure names.

**Comment by TelepathicGrunt** [comment]
The structure names are here:
https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/blob/6aca3fb94f0936fa007f8665e8dc82452336033e/src/main/java/com/telepathicgrunt/repurposedstructures/modinit/RSStructures.java#L156

You can also find them by doing /locate in a 1.16 world with RS on.

**Comment by SlimeBoi2006** [comment]
Thank you so much
