### ISSUE TITLE
MineGate adds new properties to vanilla blocks unsafely and errors the game when RS is on

### ISSUE THREAD

**Issue by SplendidAlakey** [TelepathicGrunt/RepurposedStructures-Fabric#124]
MC version 1.17
Fabric API 0.36.0
Repurposed structures 2.0.6
MineGate MoreBlocks 1.1.5

Thread on MG github: https://github.com/MrFantiVideo/MineGate/issues/5
My comment with a related latest.log and list of mods: https://github.com/MrFantiVideo/MineGate/issues/5#issuecomment-877592906

Removing either RS or MG solves the issue and its possible to load in old worlds and create new ones without a problem.

**Comment by TelepathicGrunt** [comment]
The issue is MineGate added new properties to blocks unsafely which then blows up vanilla's worldgen json system. See [my comment here](https://github.com/MrFantiVideo/MineGate/issues/5) for more info. Hopefully they can fix this soon!

**Comment by SplendidAlakey** [comment]
Fixed https://github.com/MrFantiVideo/MineGate/issues/5#issuecomment-884909048
