### ISSUE TITLE
Dimensional Doors prevents RS's structures from spawning

### ISSUE THREAD

**Issue by Nickstertjefloor** [TelepathicGrunt/RepurposedStructures-Fabric#128]
[latest.log](https://github.com/TelepathicGrunt/TelepathicGrunt/files/6872525/latest.log)

I hope this works, im not good at this.

p.s.: im nickstertje_floor on the Forge Mod site

**Comment by TelepathicGrunt** [comment]
Looks like the issue is with Dimensional Doors. I'm gonna poke them about this and see what the cause could be. Very odd. hmm. I wonder if it's something caused in one of their recent updates

**Comment by Nickstertjefloor** [comment]
i really hope it's fixable, cause both mods are awsome

**Comment by TelepathicGrunt** [comment]
Ah looks like they fixed it in dev but haven't released the fix yet. 
https://github.com/DimensionalDevelopment/DimDoors/issues/214

Thank you for reporting this! Hopefully this report will help others that gets confused as to what is going on

**Comment by TelepathicGrunt** [comment]
Dimensional doors just released an update to fix this incompat!
