### ISSUE TITLE
Missing "fabric" in fabric.mods.json

### ISSUE THREAD

**Issue by supersaiyansubtlety** [TelepathicGrunt/RepurposedStructures-Fabric#13]
I noticed that Fabric API is listed as a dependency on CurseForge, and the game crashes if you use RS without it, but it's not in fabric.mod.json so the launcher doesn't give you a pop-up listing the missing dependency. 
Longest sentence to explain the simplest thing^

**Comment by TelepathicGrunt** [comment]
Fabric API is not actually used by Repurposed Structures itself but by one or more of it's dependencies. I can add that line to my fabric.mod.json file but really, the dependencies should be the ones to be generating the warning instead of crashing. I don't know which of them is the issue rip.

**Comment by supersaiyansubtlety** [comment]
Ah, it appears to be cloth config. I'll open an issue over there.
