### ISSUE TITLE
Crash at world load

### ISSUE THREAD

**Issue by YuRaNnNzZZ** [TelepathicGrunt/RepurposedStructures-Fabric#131]
Game crashes on world load after updating to 2.1.5, can be reproduced on minimal setup (FAPI + RS + Cloth Config only):
https://gist.github.com/YuRaNnNzZZ/6948a6ee0c30a0c201dcd4bbc0ececf2

**Comment by TelepathicGrunt** [comment]
I switched to Mojmap but apparently running the game in dev didn't trigger the crash until one opens a structure block or something. my bad. update to fix that is released and will be marked as beta in case I missed any other remapping issue

**Comment by YuRaNnNzZZ** [comment]
that did it, thank you!
