### ISSUE TITLE
Fail load in world

### ISSUE THREAD

**Issue by leon7104** [TelepathicGrunt/RepurposedStructures-Fabric#133]
[latest.log](https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/files/6874548/latest.log)

**Comment by TelepathicGrunt** [comment]
this was already fixed and updated just before this report was made. Update to v2.1.6 repurposed structures and the crash should go away. The issue was due to a bad mixin on my part. Sorry about that

**Comment by leon7104** [comment]
thanks, you are awesome.

TelepathicGrunt ***@***.***> 於 2021年7月26日 週一 上午7:30寫道：
