### ISSUE TITLE
[1.17+ only] Towette breaks RS's processors and prevents world load

### ISSUE THREAD

**Issue by ozokuz** [TelepathicGrunt/RepurposedStructures-Fabric#136]
https://paste.ee/p/ySKqB

**Comment by TelepathicGrunt** [comment]
Typically, structure processors suddenly failing to be parsed means there's another mod adding properties to blocks unsafely. now the tricky part is finding which mod is the one responsible lol. I'll test some of the mods you have on to see if I can find who

**Comment by TelepathicGrunt** [comment]
It appears to be Towette which is surprising as it worked fine and safely with Repurposed Structures in 1.16.5. Mojang must had changed something in 1.17 and made property adding more tougher. I'll let the developer of Towette know about this

**Comment by TelepathicGrunt** [comment]
Statement (the lib Towelette depends on) just updated to fix this issue! Try it out https://www.curseforge.com/minecraft/mc-mods/statement/files/3419388

I’ll close this report now. Lmk if the issue persists

**Comment by unencryptid** [comment]
I'm using the latest version of statement and still getting the same issue

**Comment by TelepathicGrunt** [comment]
Yeah. We moved to this issue report. https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/issues/139

I let the dev know and he's gonna release a fix for statement soon. Hopefully that will resolve this issue once and for all!
![image](https://user-images.githubusercontent.com/40846040/128953881-dca15d89-ac16-42f4-a1b9-e95590adebcf.png)
