### ISSUE TITLE
Smokey Suppression crashes when RS dungeons affects a campfire during worldgen

### ISSUE THREAD

**Issue by ghost** [TelepathicGrunt/RepurposedStructures-Fabric#138]
https://pastecode.io/s/6t1jwh2x

Can you look at this? Problem occurs when I create new world (but not always).

**Comment by TelepathicGrunt** [comment]
The crash remapped looks like this: https://paste.ee/p/85IBK
Are you using a datapack that puts campfires into RS dungeons? Something is killing the campfire when it tries to place itself. This seems familiar to an old campfire bug but I thought vanilla fixed it a while ago

**Comment by TelepathicGrunt** [comment]
actually wait, i remapped that wrong. Hang on

Edit: ok yeah, remapped using 1.16.5 stuff and it is still campfire https://paste.ee/p/aiNoS

**Comment by TelepathicGrunt** [comment]
Wait a second, setSmokey isnt a vanilla method. It's a method another mod added. Can you please give me your modlist? I can try and find which mod it is

**Comment by ghost** [comment]
https://www.curseforge.com/minecraft/mc-mods/smoke-suppression

**Comment by TelepathicGrunt** [comment]
Thank you! I see their issue. At this line, they tried to get the block entity before it actually exists which crashes the code and freezes your game. I'll open an issue report to them
https://gitlab.com/supersaiyansubtlety/smoke_suppression/-/blob/master/src/main/java/net/sssubtlety/smoke_suppression/mixin/CampfireBlockMixin.java#L40

**Comment by ghost** [comment]
modlist: https://pastebin.com/J4xMrXrK

**Comment by ghost** [comment]
thanks 🥇

**Comment by TelepathicGrunt** [comment]
Here's the issue report on their page. keep watch on it to know when they fix the crash!
https://gitlab.com/supersaiyansubtlety/smoke_suppression/-/issues/1

**Comment by ghost** [comment]
Problem solved by mod author :)
