### ISSUE TITLE
Possible mod incompatibility Terralith

### ISSUE THREAD

**Issue by drakosoldier298** [TelepathicGrunt/RepurposedStructures-Fabric#141]
This might be a mod incompatibility or a base mod issue, 
When a underwater mineshaft is loaded by a player worker main-2 "dies" and the server crashes.
Repurposed structures fabric 1.7.1 ver. 2.3.1
Server log 
https://gist.github.com/drakosoldier298/222d0c25afc87e4d486c893de1d00c26

**Comment by TelepathicGrunt** [comment]
Do you have better-nether datapack or better-village-pillage datapack on? Basically the `Accessing PalettedContainer from multiple threads` is a known issue with those datapacks that break some other mods
https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/issues/129

**Comment by drakosoldier298** [comment]
We have the better nether mod
But we avoid datapacks.

**Comment by TelepathicGrunt** [comment]
the better nether mod is different from the datapack (they aren't related at all actually). 

so it is only with terralith that the issue occurs?

**Comment by drakosoldier298** [comment]
The issue was temporarily fixed with updating to 2.3.1 but it started happening again today.

**Comment by drakosoldier298** [comment]
I cant test without terralith as id have to reset my server which has players on and testing in singleplayer is very inconsistent

**Comment by TelepathicGrunt** [comment]
I was able to reproduce it but now, I need to contact terralith dev as it's probably something in terralith like those datapacks that is doing something unsafe with chunks or something. Terralith is actually a datapack that is wrapped as a mod. 
https://paste.ee/p/YI3VC

**Comment by drakosoldier298** [comment]
Here is their discord and i have informed him https://discord.gg/kszesuwv

**Comment by TelepathicGrunt** [comment]
I'm trying something potentially unsafe but it is based off of what vanilla ores do. They bypass the PalettedContainer's check for threads and forces their block to be placed. If you could, can you please make a backup of your world and then give this jar a test? Let me know if it fixes the crash or if it causes any issues.
[repurposed_structures_fabric-2.3.2b+1.17.1.zip](https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/files/7026493/repurposed_structures_fabric-2.3.2b%2B1.17.1.zip)

Hopefully this will work!

**Comment by drakosoldier298** [comment]
Server isnt detecting it as a fabric mod and ignores it.

**Comment by TelepathicGrunt** [comment]
Did you unzip the folder and grab the jar from inside? I had to zip it up so github lets me post it here

You can right click and select "extract here" to unzip it. Enter the new folder and the jar file is inside

**Comment by drakosoldier298** [comment]
Did not realize that you zipped it for that reason
trying it again

**Comment by drakosoldier298** [comment]
It didnt crash upon loading the chunks so seems we are good

**Comment by TelepathicGrunt** [comment]
Nice! I released the new update as beta on curseforge just in case there's any issue that hasnt be reported yet. But hopefully no one reports anymore weird crashes with some processors
