### ISSUE TITLE
Cannot add custom mob entities in the entity config

### ISSUE THREAD

**Issue by itsdinkd** [TelepathicGrunt/RepurposedStructures-Fabric#147]
1.17.1 / 3.6 RS / Fabric

[20:24:41] [main/WARN]: Repurposed Structures (second): Unknown EntityType bewitchment:ghost was found in the replace mob spawning config. Skipping that entry...
[20:24:41] [main/WARN]: Repurposed Structures (second): Unknown EntityType bewitchment:ghost was found in the replace mob spawning config. Skipping that entry...
[20:24:41] [main/WARN]: Repurposed Structures (second): Unknown EntityType doom:pinky was found in the replace mob spawning config. Skipping that entry...
[20:24:41] [main/WARN]: Repurposed Structures (second): Unknown EntityType doom:possessed_scientist was found in the replace mob spawning config. Skipping that entry...
[20:24:41] [main/WARN]: Repurposed Structures (second): Unknown EntityType bewitchment:ghost was found in the replace mob spawning config. Skipping that entry...
[20:24:41] [main/WARN]: Repurposed Structures (second): Unknown EntityType bewitchment:vampire was found in the replace mob spawning config. Skipping that entry...
[20:24:41] [main/WARN]: Repurposed Structures (second): Unknown EntityType bewitchment:vampire was found in the replace mob spawning config. Skipping that entry...
[20:24:41] [main/WARN]: Repurposed Structures (second): Unknown EntityType bewitchment:ghost was found in the append mob spawning config. Skipping that entry...

**Comment by TelepathicGrunt** [comment]
Can you share your config file and did you make sure those mods are indeed on? I was able to spawn bewitchment ghosts in badland outposts myself when testing 
![image](https://user-images.githubusercontent.com/40846040/136464987-6a2554fb-9b84-46e6-af3e-3c9cf55f726d.png)

**Comment by TelepathicGrunt** [comment]
I tested on a server as well and it appears to be working for me
![image](https://user-images.githubusercontent.com/40846040/136465512-a8600e63-389d-4adc-a8b9-94a201a8681d.png)

**Comment by itsdinkd** [comment]
What the hell!

Here is my config

{
  //




// In the key part, specify the name of the structures from Repurposed Structures that
// you want to affect. Then in the value part, add entries for all the mobs you would like
// to spawn over time in the structure's bounds. This entry will ignore biome's mob spawns
// entirely when spawning a mob in the structure's boundary after worldgen is done.
// This means you will not see the biome's mobs in the structure.

// The change only applies to SpawnGroups of the mobs you add to this config.
// Example: adding Wither Skeletons here to Birch Villages will make all Monster
// SpawnGroup spawns be Wither Skeletons in the village but Creature and other
// SpawnGroups will spawn just fine over time in the village such as sheep or cow.

// Use "all" as the key to affect all of RS's structures.
// You can find entity's identifiers by doing "/effect @e[type=" command in game.
// All of RS's structure identifiers can be found by doing "/locate" command in game.

// NOTE: replaceMobSpawns will always override appendMobSpawns for the same structure and mob's SpawnGroups.

  "replaceMobSpawns": {
    "repurposed_structures:outpost_snowy": [
      {
        "type": "minecraft:pillager",
        "weight": 1,
        "minGroupSize": 1,
        "maxGroupSize": 1,
        "logErrorIfNotFound": false
      }
    ],
    "repurposed_structures:outpost_crimson": [
      {
        "type": "minecraft:piglin",
        "weight": 10,
        "minGroupSize": 1,
        "maxGroupSize": 1,
        "logErrorIfNotFound": false
      }
    ],
    "repurposed_structures:outpost_taiga": [
      {
        "type": "minecraft:pillager",
        "weight": 1,
        "minGroupSize": 1,
        "maxGroupSize": 1,
        "logErrorIfNotFound": false
      }
    ],
    "repurposed_structures:outpost_birch": [
      {
        "type": "minecraft:pillager",
        "weight": 1,
        "minGroupSize": 1,
        "maxGroupSize": 1,
        "logErrorIfNotFound": false
      }
    ],
    "repurposed_structures:outpost_jungle": [
      {
        "type": "minecraft:pillager",
        "weight": 1,
        "minGroupSize": 1,
        "maxGroupSize": 1,
        "logErrorIfNotFound": false
      }
    ],
    "repurposed_structures:witch_hut_oak": [
      {
        "type": "minecraft:witch",
        "weight": 1,
        "minGroupSize": 1,
        "maxGroupSize": 1,
        "logErrorIfNotFound": false
      },
      {
        "type": "minecraft:cat",
        "weight": 1,
        "minGroupSize": 1,
        "maxGroupSize": 1,
        "logErrorIfNotFound": false
      },
      {
        "type": "bewitchment:ghost",
        "weight": 1,
        "minGroupSize": 1,
        "maxGroupSize": 2,
        "logErrorIfNotFound": true
      }
    ],
    "repurposed_structures:outpost_warped": [
      {
        "type": "minecraft:piglin",
        "weight": 10,
        "minGroupSize": 1,
        "maxGroupSize": 1,
        "logErrorIfNotFound": false
      }
    ],
    "repurposed_structures:witch_hut_giant_tree_taiga": [
      {
        "type": "minecraft:witch",
        "weight": 1,
        "minGroupSize": 1,
        "maxGroupSize": 1,
        "logErrorIfNotFound": false
      },
      {
        "type": "minecraft:cat",
        "weight": 1,
        "minGroupSize": 1,
        "maxGroupSize": 1,
        "logErrorIfNotFound": false
      },
      {
        "type": "bewitchment:ghost",
        "weight": 1,
        "minGroupSize": 1,
        "maxGroupSize": 2,
        "logErrorIfNotFound": true
      }
    ],
    "repurposed_structures:outpost_oak": [
      {
        "type": "minecraft:pillager",
        "weight": 1,
        "minGroupSize": 1,
        "maxGroupSize": 1,
        "logErrorIfNotFound": false
      }
    ],
    "repurposed_structures:stronghold_nether": [
      {
        "type": "minecraft:blaze",
        "weight": 10,
        "minGroupSize": 2,
        "maxGroupSize": 3,
        "logErrorIfNotFound": false
      },
      {
        "type": "minecraft:zombified_piglin",
        "weight": 3,
        "minGroupSize": 4,
        "maxGroupSize": 4,
        "logErrorIfNotFound": false
      },
      {
        "type": "minecraft:wither_skeleton",
        "weight": 10,
        "minGroupSize": 5,
        "maxGroupSize": 5,
        "logErrorIfNotFound": false
      },
      {
        "type": "minecraft:skeleton",
        "weight": 2,
        "minGroupSize": 5,
        "maxGroupSize": 5,
        "logErrorIfNotFound": false
      },
      {
        "type": "minecraft:magma_cube",
        "weight": 3,
        "minGroupSize": 4,
        "maxGroupSize": 4,
        "logErrorIfNotFound": false
      },
      {
        "type": "doom:pinky",
        "weight": 1,
        "minGroupSize": 1,
        "maxGroupSize": 1,
        "logErrorIfNotFound": true
      },
      {
        "type": "doom:possessed_scientist",
        "weight": 3,
        "minGroupSize": 1,
        "maxGroupSize": 2,
        "logErrorIfNotFound": true
      }
    ],
    "repurposed_structures:outpost_badlands": [
      {
        "type": "minecraft:pillager",
        "weight": 1,
        "minGroupSize": 1,
        "maxGroupSize": 1,
        "logErrorIfNotFound": false
      }
    ],
    "repurposed_structures:outpost_giant_tree_taiga": [
      {
        "type": "minecraft:pillager",
        "weight": 1,
        "minGroupSize": 1,
        "maxGroupSize": 1,
        "logErrorIfNotFound": false
      }
    ],
    "repurposed_structures:witch_hut_taiga": [
      {
        "type": "minecraft:witch",
        "weight": 1,
        "minGroupSize": 1,
        "maxGroupSize": 1,
        "logErrorIfNotFound": false
      },
      {
        "type": "minecraft:cat",
        "weight": 1,
        "minGroupSize": 1,
        "maxGroupSize": 1,
        "logErrorIfNotFound": false
      },
      {
        "type": "bewitchment:ghost",
        "weight": 1,
        "minGroupSize": 1,
        "maxGroupSize": 1,
        "logErrorIfNotFound": true
      }
    ],
    "repurposed_structures:outpost_nether_brick": [
      {
        "type": "minecraft:piglin",
        "weight": 10,
        "minGroupSize": 1,
        "maxGroupSize": 1,
        "logErrorIfNotFound": false
      }
    ],
    "repurposed_structures:witch_hut_birch": [
      {
        "type": "minecraft:witch",
        "weight": 1,
        "minGroupSize": 1,
        "maxGroupSize": 1,
        "logErrorIfNotFound": false
      },
      {
        "type": "minecraft:cat",
        "weight": 1,
        "minGroupSize": 1,
        "maxGroupSize": 1,
        "logErrorIfNotFound": false
      },
      {
        "type": "bewitchment:ghost",
        "weight": 1,
        "minGroupSize": 1,
        "maxGroupSize": 1,
        "logErrorIfNotFound": false
      }
    ],
    "repurposed_structures:witch_hut_dark_forest": [
      {
        "type": "minecraft:witch",
        "weight": 1,
        "minGroupSize": 1,
        "maxGroupSize": 1,
        "logErrorIfNotFound": false
      },
      {
        "type": "minecraft:cat",
        "weight": 1,
        "minGroupSize": 1,
        "maxGroupSize": 1,
        "logErrorIfNotFound": false
      },
      {
        "type": "bewitchment:ghost",
        "weight": 1,
        "minGroupSize": 1,
        "maxGroupSize": 1,
        "logErrorIfNotFound": false
      }
    ],
    "repurposed_structures:outpost_end": [
      {
        "type": "minecraft:phantom",
        "weight": 10,
        "minGroupSize": 1,
        "maxGroupSize": 1,
        "logErrorIfNotFound": false
      }
    ],
    "repurposed_structures:bastion_underground": [
      {
        "type": "minecraft:skeleton",
        "weight": 1,
        "minGroupSize": 1,
        "maxGroupSize": 4,
        "logErrorIfNotFound": false
      },
      {
        "type": "bewitchment:vampire",
        "weight": 1,
        "minGroupSize": 1,
        "maxGroupSize": 1,
        "logErrorIfNotFound": true
      }
    ],
    "repurposed_structures:outpost_icy": [
      {
        "type": "minecraft:pillager",
        "weight": 1,
        "minGroupSize": 1,
        "maxGroupSize": 1,
        "logErrorIfNotFound": false
      }
    ],
    "repurposed_structures:outpost_desert": [
      {
        "type": "minecraft:pillager",
        "weight": 1,
        "minGroupSize": 1,
        "maxGroupSize": 1,
        "logErrorIfNotFound": false
      }
    ],
    "repurposed_structures:city_nether": [
      {
        "type": "minecraft:blaze",
        "weight": 120,
        "minGroupSize": 1,
        "maxGroupSize": 4,
        "logErrorIfNotFound": false
      },
      {
        "type": "minecraft:wither_skeleton",
        "weight": 10,
        "minGroupSize": 2,
        "maxGroupSize": 3,
        "logErrorIfNotFound": false
      },
      {
        "type": "bewitchment:vampire",
        "weight": 1,
        "minGroupSize": 1,
        "maxGroupSize": 1,
        "logErrorIfNotFound": true
      }
    ]
  },
  //




// In the key part, specify the name of the structures from Repurposed Structures that
// you want to affect. Then in the value part, add entries for all the mobs you would like
// to spawn over time in the structure's bounds. This entry will combine with the biome's
// mob spawns when spawning a mob in the structure's boundary after worldgen is done.
// This means you will see both biome's and structure's mobs in the structure.

// Use "all" as the key to affect all of RS's structures.
// You can find entity's identifiers by doing "/effect @e[type=" command in game.
// All of RS's structure identifiers can be found by doing "/locate" command in game.

  "appendMobSpawns": {
    "repurposed_structures:shipwreck_nether_bricks": [
      {
        "type": "minecraft:wither_skeleton",
        "weight": 25,
        "minGroupSize": 1,
        "maxGroupSize": 1,
        "logErrorIfNotFound": true
      },
      {
        "type": "bewitchment:ghost",
        "weight": 1,
        "minGroupSize": 1,
        "maxGroupSize": 2,
        "logErrorIfNotFound": true
      }
    ],
    "repurposed_structures:shipwreck_crimson": [
      {
        "type": "minecraft:wither_skeleton",
        "weight": 25,
        "minGroupSize": 1,
        "maxGroupSize": 1,
        "logErrorIfNotFound": true
      }
    ],
    "repurposed_structures:mineshaft_end": [
      {
        "type": "minecraft:endermite",
        "weight": 10,
        "minGroupSize": 2,
        "maxGroupSize": 5,
        "logErrorIfNotFound": true
      },
      {
        "type": "minecraft:enderman",
        "weight": 5,
        "minGroupSize": 1,
        "maxGroupSize": 3,
        "logErrorIfNotFound": true
      }
    ],
    "repurposed_structures:fortress_jungle": [
      {
        "type": "minecraft:wither_skeleton",
        "weight": 27,
        "minGroupSize": 1,
        "maxGroupSize": 1,
        "logErrorIfNotFound": true
      }
    ],
    "repurposed_structures:shipwreck_warped": [
      {
        "type": "minecraft:wither_skeleton",
        "weight": 25,
        "minGroupSize": 1,
        "maxGroupSize": 1,
        "logErrorIfNotFound": true
      }
    ],
    "repurposed_structures:stronghold_end": [
      {
        "type": "minecraft:endermite",
        "weight": 100,
        "minGroupSize": 2,
        "maxGroupSize": 4,
        "logErrorIfNotFound": true
      }
    ]
  },
  //




// for internal use only. Do not change this.

  "configVersion": 3
}

**Comment by TelepathicGrunt** [comment]
That config without any changes was able to be parsed just fine for me and works. I was able to spawn doom's mobs and bewitchment mobs. Just note that Vampires cannot spawn in the nether because vampires have an internal check for moon phases (looks for phase 4 while the nether always returns a moon phase of 0)
https://github.com/MoriyaShiine/bewitchment/blob/388aec0ab7412e92bd820e340f5fe777e00fe2ed/src/main/java/moriyashiine/bewitchment/common/registry/BWWorldGenerators.java#L97

Perhaps your issue is related to your other bug report?
https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/issues/146#issuecomment-938261748

Like something in the modpack has wrecked everything so hard that nothing works when it should. Mega odd. I'll definitely have to copy your modlist and see whats up

**Comment by itsdinkd** [comment]
Oh man :( That scares me..... What the hell is going on with this pack =/
