### ISSUE TITLE
Tried using Fabric RS on Forge

### ISSUE THREAD

**Issue by SubliJo** [TelepathicGrunt/RepurposedStructures-Fabric#150]
Hi,

I'm new to using mods and I've been trying to get this one to work.

I've added a few mods that are working fine, this was actually the second after journeymap I tried to use. The other mods I've installed were mainly to see if I was doing something wrong but they all work.

![image](https://user-images.githubusercontent.com/93080659/138593078-bf9fe8ea-9e71-4b88-bf8f-27f4b2719205.png)

So right now it says 5 mods are loaded

![image](https://user-images.githubusercontent.com/93080659/138593112-ad14cd76-9f93-40bf-a2f8-e646475569c4.png)

And this is my mod folder:

![image](https://user-images.githubusercontent.com/93080659/138593150-39e51ff6-340d-4499-a4a1-fe2558237d1a.png)

I've tried using an older version for 1.17, only using the repurposed structures file without the cloth and fabric file and reinstalling forge but nothing seems to work. Anyone able to explain what I am doing wrong?

Thanks in advance.

**Comment by TelepathicGrunt** [comment]
You’re using the fabric version of repurposed structures which is for Fabric modloader. Not Forge. You can download the forge version of repurposed structures from here: https://www.curseforge.com/minecraft/mc-mods/repurposed-structures

However, do note, I did not port repurposed structures to 1.17 on forge. 1.16.5 is the latest as I am planning on skipping 1.17 and port directly to 1.18 when it comes out.
