### ISSUE TITLE
Waystone integration doesn't seem to respect Waystone settings

### ISSUE THREAD

**Issue by BrekiTomasson** [TelepathicGrunt/RepurposedStructures-Fabric#155]
On launch, I'm seeing this:

`Adding waystone waystones:stone_brick_village_waystone to village repurposed_structures:villages/mountains/houses`

But my `waystone` configuration clearly states `"generate_in_villages": false,`

**Comment by BrekiTomasson** [comment]
Relevant versions being used:

- waystones 2.2.0
- repurposed_structures 2.5.6+1.17.1
- fabricloader 0.12.5
- fabric 0.42.1+1.17

**Comment by TelepathicGrunt** [comment]
As of RS 2.5.6, the compat code with waystones is actually on Fabric Waystone’s side. Their mod injects the pieces into my mod’s structure pools. I’ll let them know about this.

**Comment by BrekiTomasson** [comment]
Thanks!

**Comment by TelepathicGrunt** [comment]
looks like v2.2.1 fabric waystone fixes this now! https://www.curseforge.com/minecraft/mc-mods/fabric-waystones/files/3524411
> - Fixed waystones always being added to villages (even with the config option set to false) with Repurposed Structures installed

I'll close this report
