### ISSUE TITLE
Mansions Floating & Colliding with Terrain

### ISSUE THREAD

**Issue by PuppetMasterZee** [TelepathicGrunt/RepurposedStructures-Fabric#156]
MC: 1.17.1
Fabric Loader: 0.12.5
Fabric API 0.42.1+1.17
repurposed_structures_fabric-2.5.7+1.17.1

Screenshots
[https://imgur.com/a/ow6Y7vl]

**Comment by TelepathicGrunt** [comment]
That does not look like any structure from repurposed structures. Please use the /locate command and find who's structure that is actually from. Repurposed Structures's mansions looks like vanilla mansions with their blocks swapped. Like this:
![image](https://user-images.githubusercontent.com/40846040/142654352-27eefc48-74fa-411e-90ac-24a665c64dc8.png)

I hope this helps cleans up the confusion!

**Comment by TelepathicGrunt** [comment]
I asked some friends and they said the structure you found is actually End Remastered's End Castle. That should help you out but yeah, nothing to do with Repurposed Structures
![image](https://user-images.githubusercontent.com/40846040/142655447-624efa37-40d0-44ef-bb99-c8738358bd44.png)

**Comment by PuppetMasterZee** [comment]
Whoops!  Sorry!   Thanks for your time.
