### ISSUE TITLE
Compatibility issue with Fabric Waystones: Mushroom Village generation stalls server

### ISSUE THREAD

**Issue by RubyRezal** [TelepathicGrunt/RepurposedStructures-Fabric#159]
Minecraft 1.18-rc3 (& rc4)
Repurposed Structures 3.1.1+1.18rc3
wraith-waystones-2.3.0

Problem: server stalling when Repurposed Structures attempts to generate Mushroom Village while Fabric Waystones is installed. (may also occur with any other non-vanilla villages, untested)

Message in Log:
Repurposed Structures: Failed to create valid structure with all required pieces starting from this pool file: repurposed_structures:villages/mushroom/town_centers. Required pieces failed to generate the required amount are: [waystones:village_waystone=1]
  Make sure this structure's size in the config (if it has one) is not set too low.
  Also make sure the max height and min height for this structure in the config (if it has one) is not too close together.
  If min and max height is super close together, the structure's pieces may not be able to fit in the narrow range and spawn.
  Otherwise, if the min and max height ranges aren't close, and structure size isn't super small like 1 or 2, and this message still appears,
  please report the issue to Repurposed Structures's dev with latest.log file!
  
  
Example: Mushroom island NE of spawn, world seed -1166828785
Waystones do generate properly in Repurposed Structures "vanilla" villages

Copy of log: https://pastebin.com/TnSpNA7a

**Comment by RubyRezal** [comment]
This issue occurs even if the generation of waystones in villages is disabled in Frabic Waystones config.

**Comment by TelepathicGrunt** [comment]
It’s due to RS changing how it receives what pieces to try and always spawn and fabric waystones trying to adapt to the new system. V3.1.1 RS finalized the new system so now fabric waystones just needs to add special json files into their mod to finish the compatibility between the two mods

**Comment by RubyRezal** [comment]
It appears Fabric Waystones will address this in their next version.
https://github.com/LordDeatHunter/FabricWaystones/issues/77#issuecomment-982761168

**Comment by RubyRezal** [comment]
Issue resolved by Fabric Waystones update 2.3.1
https://github.com/LordDeatHunter/FabricWaystones/issues/77#issuecomment-983260411
