### ISSUE TITLE
Generating mineshafts crashes server

### ISSUE THREAD

**Issue by kevahu** [TelepathicGrunt/RepurposedStructures-Fabric#166]
I am pre-generating a map for my multiplayer server using the Repurposed Structures Mod for Fabric.
After a while of generating my server crashes when trying to generate the mineshaft_ocean or mineshaft_nether structures.

I am using Chunky to generate the chunks but because the crash report mentions those structures, I report it here.

It happens less when allocating more memory.

Any more information can be found in the crash reports:

[crash-2021-12-07_16.10.58-server.txt](https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/files/7698555/crash-2021-12-07_16.10.58-server.txt)
[crash-2021-12-07_18.19.52-server.txt](https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/files/7698556/crash-2021-12-07_18.19.52-server.txt)
[crash-2021-12-07_19.33.25-server.txt](https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/files/7698557/crash-2021-12-07_19.33.25-server.txt)
[crash-2021-12-07_20.19.31-server.txt](https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/files/7698558/crash-2021-12-07_20.19.31-server.txt)
[crash-2021-12-08_20.05.59-server.txt](https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/files/7698559/crash-2021-12-08_20.05.59-server.txt)
[crash-2021-12-10_18.53.43-server.txt](https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/files/7698560/crash-2021-12-10_18.53.43-server.txt)
[crash-2021-12-11_19.53.37-server.txt](https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/files/7698561/crash-2021-12-11_19.53.37-server.txt)
[crash-2021-12-11_21.15.31-server.txt](https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/files/7698562/crash-2021-12-11_21.15.31-server.txt)
[crash-2021-12-07_13.46.45-server.txt](https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/files/7698563/crash-2021-12-07_13.46.45-server.txt)
[crash-2021-12-07_15.39.01-server.txt](https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/files/7698564/crash-2021-12-07_15.39.01-server.txt)

I have now tried updating all mods to the latest versions, running the server on Linux instead of Windows, running on an other computer, updating Java 17 but it still crashes.

**Comment by TelepathicGrunt** [comment]
This is a vanilla bug with json processors and creations multiple chunks at once. If you put on this mod called No Null Processor, it should fix the bug and prevent the crash. You can read the description for more info as to why it happens.  https://www.curseforge.com/minecraft/mc-mods/no-null-processors
