### ISSUE TITLE
Mineshaft Walls don't connect

### ISSUE THREAD

**Issue by RyanCR03** [TelepathicGrunt/RepurposedStructures-Fabric#167]
the walls of the mineshafts arent connected and I assume that its because the structures were created before 1.1
![2021-12-12_18 42 55](https://user-images.githubusercontent.com/32957560/145736533-15421b41-64e2-4b4e-905c-ae785c39d64f.png)
6

**Comment by TelepathicGrunt** [comment]
fixed in  v3.1.11
