### ISSUE TITLE
Support korean translation and print text error in config gui in-game.

### ISSUE THREAD

**Issue by gyular** [TelepathicGrunt/RepurposedStructures-Fabric#171]
If you fine, plesase add korean translation.
This is that i translated file.
https://gist.github.com/gyular/75ec6fc8206bd295673acc88e993e536

And
In Mod Menu's in-game config GUI,

RSMansionsConfig.pillarOnlyToLand in Mansions Menu
RSVillagesConfig.spawnrate.villageMushroomAverageChunkDistance in Villeges Menu's spawnrate

Not print correct text.

**Comment by TelepathicGrunt** [comment]
Yeah I can add that file to the mod after I format it. If you want to see the clean formatted translations, you can find them here which will make it much easier to read and translate stuff
<https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/tree/latest-released/src/main/resources/assets/repurposed_structures/lang>

Thank you tho!

**Comment by gyular** [comment]
Okay, I updated file.
https://gist.github.com/gyular/75ec6fc8206bd295673acc88e993e536

**Comment by TelepathicGrunt** [comment]
the translation is now released in v3.1.11! thank you!
