### ISSUE TITLE
[Suggestion] Illusioner Hut

### ISSUE THREAD

**Issue by RyanCR03** [TelepathicGrunt/RepurposedStructures-Fabric#172]
a structure like the witch hut that instead contains an illusioner and a killer rabbit

**Comment by TelepathicGrunt** [comment]
RS is about making new biome or dimension variants of vanilla structures. Not really for making custom new structures from scratch. That's better done for other structure mods to do like mo structures or Worldshape.

**Comment by RyanCR03** [comment]
but its not from scratch its the witch hut

**Comment by TelepathicGrunt** [comment]
illagers and killer rabbits is too far removed from vanilla tho. possibly will make a lot of people hate me for spawning killer bunnies too that kill them and illusioners arent suppose to spawn as they are an unused mob. plus those mobs dont even fit the style of a witch hut.
