### ISSUE TITLE
[Suggestion] Config for dungeon types

### ISSUE THREAD

**Issue by griffin4cats** [TelepathicGrunt/RepurposedStructures-Fabric#173]
While the blaze, zombie piglin, strider, and magma cube dungeons in the nether are interesting, I think our server believes that the wither skeleton ones are a bit too op. It would be nice to have config to turn certain spawners off.

**Comment by TelepathicGrunt** [comment]
Spawner mob types are already configurable for RS. You can do so by editing this datapack and putting it into the server’s datapack folder or other dedicated datapack loading mod’s folders. https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/releases/tag/0.0.5

The config section on my curseforge page goes into detail of what is configurable and has links to example datapacks for ease of editing.
