### ISSUE TITLE
[Suggestion] Unwrecked ship

### ISSUE THREAD

**Issue by RyanCR03** [TelepathicGrunt/RepurposedStructures-Fabric#174]
similar to the nether ships there could be a ship on water that uses one of the shipwreck models. add a few wool blocks for the sail and make pillagers spawn there

**Comment by TelepathicGrunt** [comment]
I decided against basically pirate ships in overworld as that's better suited for other mods to do such as Mo' Structures. I think Mo' Structures already has a pirate ship actually.
