### ISSUE TITLE
Repurposed Structures v3.3.2 (1.18.1 fabric)

### ISSUE THREAD

**Issue by Thiana** [TelepathicGrunt/RepurposedStructures-Fabric#176]
You accidentally uploaded the dev environment version of v3.3.2 for fabric to curseforge. Thanks.

**Comment by TelepathicGrunt** [comment]
try v3.3.3 now. The automated system I was switching to using for uploading to curseforge grabbed the wrong jar to upload. I went ahead and manually uploaded the correct jar myself while I go work with the dev of the automated task system to figure out what is wrong.
