### ISSUE TITLE
startup crash

### ISSUE THREAD

**Issue by Heamaci** [TelepathicGrunt/RepurposedStructures-Fabric#180]
I'm not sure what's causing this crash, but i can't launch the game anymore with one of the updates
[latest.log](https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/files/7923919/latest.log)

**Comment by TelepathicGrunt** [comment]
You’re missing the new dependencies required that helps to fix some nasty Minecraft bugs. Basically this part of the log states the issue: 

```
A potential solution has been determined:
	 - Install no_null_processors, any version.
	 - Install feature_nbt_deadlock_be_gone, any version.
Unmet dependency listing:
	 - Mod 'Repurposed Structures' (repurposed_structures) 3.3.4+1.18.1 requires any version of no_null_processors, which is missing!
	 - Mod 'Repurposed Structures' (repurposed_structures) 3.3.4+1.18.1 requires any version of feature_nbt_deadlock_be_gone, which is missing!
```

You can download the two required mods from here: 
https://www.curseforge.com/minecraft/mc-mods/no-null-processors
https://www.curseforge.com/minecraft/mc-mods/feature-nbt-deadlock-be-gone

I hope this helps clarify what’s going on.
