### ISSUE TITLE
generation broken for other structure mods with RS

### ISSUE THREAD

**Issue by ghost** [TelepathicGrunt/RepurposedStructures-Fabric#184]
https://github.com/WaldiNet/Towers_Of_The_Wild_Reworked/issues/6

Locate always returns 'Could not find that structure nearby' for any structure from Towers of the Wild: Reworked when RS is installed. Locating vanilla structures and structures from RS works. Distance doesn't factor in and the same behaviour is reproducible with Mo' Structures + RS.

**Comment by ghost** [comment]
I've changed the title as locate wasn't the problem. When Repurposed is installed towers just don't generate at all.

Two worlds, identical seeds. With no repurposed installed tower generates near spawn, within 5 minutes found multiple other towers while flying around - also visible on map.

With repurposed, no towers found within 20k of spawn. Disable repurposed and locate works but only finds towers outside already generated areas.

I presume it's the same situation with Mo' Structures but I haven't tested that yet.

**Comment by Panderine** [comment]
This also affects structures from: 

- AE2 
- Awesome Dungeons 
- Bosses of mass destruction
- When dungeons arise
- mo' structures
- sky villages
- soaring structures 2
- stoneholm
- towers of the wild

Doesn't affect:
- The Graveyard

**Comment by TelepathicGrunt** [comment]
@Panderine errr. I was testing AE the other day with RS and it’s meteors were spawning just fine. Both of you, please make sure you’re using the latest RS update and latest Fabric API update. 

It’ll be a bit before I get around to testing RS and fixing bugs as I’m still working on Bumblezone right now in my spare time

**Comment by Aureljz** [comment]
I thought I'd share some extra details about the issue. I ran a few tests with latest Fabric API version, RS and Stoneholm alone to keep it simple (plus dependencies), as it follows:
* fabric loader 0.12.12
* fabric-api-0.46.4+1.18
* repurposed_structures_fabric-3.3.6+1.18.1
* stoneholm-1.4.2
* cloth-config-6.1.48-fabric
* no_null_processors_fabric-2.0.1+1.18.1
* feature_nbt_deadlock_be_gone_fabric-1.0.1+1.18.1

Result: Stoneholm structures won't spawn on the world if RS is present. When RS and its dependencies are disabled, Stoneholm works correctly. RS structures are not affected.
I also tested the mods mentioned by @Panderine with similar results.

It seems related to fabric API. Everything seems to work correctly when I downgrade fabric api to previous versions: fabric-api-0.46.1+1.18.

**Comment by TelepathicGrunt** [comment]
ugh. what did fabric api do...
For now, everyone downgrade fabric api until i get around to looking into it

**Comment by Panderine** [comment]
proly this:
fabric-api-0.46.3+1.18.jar 
-Move biome modification into the MinecraftServer constructor (#1966) (shartte)

**Comment by TelepathicGrunt** [comment]
update to 3.3.7 Repurposed Structures and give that a test please. See if that resolves the issue as in my local testing, it seems to work.
This update for RS requires the newest Fabric API version.

The changes I have done:
https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/commit/f833d8394d757134107b3166b310f0b9d4831957

**Comment by TelepathicGrunt** [comment]
Just tested my latest update with latest fabric api and some structure mods in production and it seems to be working just fine now
![image](https://user-images.githubusercontent.com/40846040/152619626-6068e300-af5c-4151-a11e-2a286daebc87.png)

**Comment by ghost** [comment]
Can confirm that it works for me with multiple structure mods as well. Thanks very much.
