### ISSUE TITLE
A structure so massive it crashes the game...

### ISSUE THREAD

**Issue by SndChaser** [TelepathicGrunt/RepurposedStructures-Fabric#186]
In MC 1.18.1 using RS 3.1.10 (Fabric) the mod generated an Jungle Fortress so massive that I literally cannot get around the whole thing without crashing the game:
![Minecraft_Massive_RS_Fortress_2022-02-27_17-23-56](https://user-images.githubusercontent.com/1224352/155906761-cc564988-2189-428a-8515-652e7e7073d2.png)
![Minecraft_Massive_RS_Fortress_2022-02-27_17-21-50](https://user-images.githubusercontent.com/1224352/155906795-ce805a28-7c38-4c64-90f0-a369b5a9efa2.png)

Attached are a couple of the crash logs from my attempts.
[crash-2022-02-27_17.39.16-server.txt](https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/files/8149760/crash-2022-02-27_17.39.16-server.txt)
[crash-2022-02-27_18.03.26-server.txt](https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/files/8149762/crash-2022-02-27_18.03.26-server.txt)

**Comment by TelepathicGrunt** [comment]
Go into the config and set the jungle fortress spawnrate to a more reasonable value. Seems it was probably set to 1 or something. The default config value is 50. Remember, 1 is spawning in every chunk with a valid biome. 50 means a spawn attempt is tried roughly every 50 chunks apart. 1001 is to turn off the structure entirely. The comment on the config should explain this to help.

**Comment by SndChaser** [comment]
I checked, and you were right, it was set to 1.  Weird thing: I'm new to mods and haven't made any changes to the settings for Repurposed Structures (honestly the wording on the settings was confusing -- your explanation here makes a lot more sense).

(Aside: the only mod I've changes settings on is the Dehydration mod as the descriptions of the settings made sense.  I don't change settings I don't understand.)

**Comment by TelepathicGrunt** [comment]
weird. But at least this issue is now resolved! have fun!
