### ISSUE TITLE
Upgrading from 1.18.1 and chunks where structures were are re-generated

### ISSUE THREAD

**Issue by Auzathoth** [TelepathicGrunt/RepurposedStructures-Fabric#187]
Hi. I have a world that's been running in 1.18/1.18.1 with RS. It's currently on v3.3.12. Testing with a copy of the world in 1.18.2 with RS 4.0.0 and the log is full of some variant of: 

04.03 17:20:42 [Server] Server thread/ERROR Couldn't load chunk [100, 29]
04.03 17:20:42 [Server] INFO java.lang.IllegalStateException: Found unknown structure: repurposed_structures:pyramid_mushroom
04.03 17:20:42 [Server] INFO at net.minecraft.class_7046.method_41022(class_7046.java:188) ~[server-intermediary.jar:?]
04.03 17:20:42 [Server] INFO at net.minecraft.class_7046.method_41011(class_7046.java:181) ~[server-intermediary.jar:?]
04.03 17:20:42 [Server] INFO at com.mojang.datafixers.util.Pair.mapFirst(Pair.java:64) ~[datafixerupper-4.1.27.jar:?]
04.03 17:20:42 [Server] INFO at net.minecraft.class_7046.method_41018(class_7046.java:181) ~[server-intermediary.jar:?]
04.03 17:20:42 [Server] INFO at net.minecraft.class_7046.method_41014(class_7046.java:177) ~[server-intermediary.jar:?]
04.03 17:20:42 [Server] INFO at com.mojang.serialization.Dynamic.lambda$null$4(Dynamic.java:71) ~[datafixerupper-4.1.27.jar:?]
04.03 17:20:42 [Server] INFO at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
04.03 17:20:42 [Server] INFO at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
04.03 17:20:42 [Server] INFO at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) ~[?:?]
04.03 17:20:42 [Server] INFO at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
04.03 17:20:42 [Server] INFO at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
04.03 17:20:42 [Server] INFO at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
04.03 17:20:42 [Server] INFO at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
04.03 17:20:42 [Server] INFO at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
04.03 17:20:42 [Server] INFO at com.mojang.serialization.Dynamic.lambda$updateMapValues$5(Dynamic.java:73) ~[datafixerupper-4.1.27.jar:?]
04.03 17:20:42 [Server] INFO at com.mojang.datafixers.util.Either$Left.mapBoth(Either.java:33) ~[datafixerupper-4.1.27.jar:?]
04.03 17:20:42 [Server] INFO at com.mojang.serialization.DataResult.map(DataResult.java:110) ~[datafixerupper-4.1.27.jar:?]
04.03 17:20:42 [Server] INFO at com.mojang.serialization.Dynamic.updateMapValues(Dynamic.java:70) ~[datafixerupper-4.1.27.jar:?]
04.03 17:20:42 [Server] INFO at net.minecraft.class_7046.method_41020(class_7046.java:177) ~[server-intermediary.jar:?]
04.03 17:20:42 [Server] INFO at net.minecraft.class_7046.method_41024(class_7046.java:137) ~[server-intermediary.jar:?]
04.03 17:20:42 [Server] INFO at com.mojang.serialization.Dynamic.lambda$null$13(Dynamic.java:136) ~[datafixerupper-4.1.27.jar:?]
04.03 17:20:42 [Server] INFO at com.mojang.serialization.DynamicOps.lambda$update$21(DynamicOps.java:222) ~[datafixerupper-4.1.27.jar:?]
04.03 17:20:42 [Server] INFO at com.mojang.datafixers.util.Either$Left.mapBoth(Either.java:33) ~[datafixerupper-4.1.27.jar:?]
04.03 17:20:42 [Server] INFO at com.mojang.serialization.DataResult.map(DataResult.java:110) ~[datafixerupper-4.1.27.jar:?]
04.03 17:20:42 [Server] INFO at com.mojang.serialization.DynamicOps.update(DynamicOps.java:222) ~[datafixerupper-4.1.27.jar:?]
04.03 17:20:42 [Server] INFO at com.mojang.serialization.Dynamic.lambda$update$14(Dynamic.java:136) ~[datafixerupper-4.1.27.jar:?]
04.03 17:20:42 [Server] INFO at com.mojang.serialization.Dynamic.map(Dynamic.java:36) ~[datafixerupper-4.1.27.jar:?]
04.03 17:20:42 [Server] INFO at com.mojang.serialization.Dynamic.update(Dynamic.java:136) ~[datafixerupper-4.1.27.jar:?]
04.03 17:20:45 [Multicraft] Skipped 236 lines due to rate limit (30/s)

**Comment by TelepathicGrunt** [comment]
Yeah that’s normal logspam as all my structures were redone to utilize Mojang’s new json structure system. The old structures will lose their bounding boxes saved in the world but the blocks will remain as is. I’ll add a logspam suppressor in full release of RS but otherwise, you got nothing to worry about with that specific messages in logs

**Comment by Auzathoth** [comment]
It's not only logspam. The chunks are regenerated and the existing structures are gone.

For example, this used to be a Mushroom village next to a temple:

![2022-03-04_22 20 02](https://user-images.githubusercontent.com/83247784/156854358-364c0080-3192-4703-b67a-2df56f6bfb42.png)

as it looked in 1.18.1:

![2022-03-04_23 15 47](https://user-images.githubusercontent.com/83247784/156854787-c2b03633-221e-44aa-b097-f915f1e7a781.png)

**Comment by TelepathicGrunt** [comment]
I never seen that behavior before nor that missing structures cause chunk regen. Previous testing with missing structures have no cause that. If that’s the case for 1.18.2 due to Mojang’s internal changes, then there isn’t much I can do to preserve it as the 80+ base structures I had registered to the base structure registry no longer exist and won’t come back. They are all now in the configured structure registry by json and uses fewer base structures to work. I’ll still look into it or just slap a warning 1.18.2 isn’t safe for updating any old modded worlds to it

**Comment by TelepathicGrunt** [comment]
so this is most likely going to be fixed by Forge and fabric API since this affects all modded structures when updating old worlds. I contacted them both so hold off on updating your world until they release an update that helps preserve the chunks from being regenned.

**Comment by Auzathoth** [comment]
Ok. Thanks. I did come up with a work-around, but it involved loading the world in vanilla 1.18.1 and visiting all the places. Then they'd remain when the world was upgraded to 1.18.2.

**Comment by ghost** [comment]
Is this still a thing? I have a world I started on 1.18.1 and Ive held off updating, don't wanna encounter this as people utilize some of the new spawn structures either as bases or farming areas. Great work BTW! Love the mod

**Comment by TelepathicGrunt** [comment]
Fabric api supposedly fixed the vanilla bug. You should make a backup of your world, update fabric api to latest, then update your world to 1.18.1, and double check to make sure everything is good. I forgot to closet this with this info
