### ISSUE TITLE
Inspecio with certain other mods causes RS to unable to get mobs for dungeons and structures

### ISSUE THREAD

**Issue by big-tdawg** [TelepathicGrunt/RepurposedStructures-Fabric#191]
Been getting this error spammed in my latest.log after updating to 1.18.2.

***************************************
[15:20:41] [Worker-Main-6/ERROR]: 
***************************************
Failed to get mob. Please check that repurposed_structures:dungeons/deep.json is correct or that no other mod is interfering with how vanilla reads data folders. Let TelepathicGrunt know about this too!

[latest.log](https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/files/8422263/latest.log)

**Comment by TelepathicGrunt** [comment]
the conflict is between Charm and  Inspecio. The two breaks the resource listener that my mod and other mods uses which causes the rest of us to break. (In RS's cause, it causes my mob spawners to have pigs and my mod compat datapacks to not work properly). Removing Charm or Inspecio should prevent the issue until either one figures out the cause of the issue and updates. (Issue seems to be more on Inspecio side as their GitHub has some report of them breaking other mods in similar way)


I made an issue report to both charm and inspecio here:
<https://github.com/Queerbric/Inspecio/issues/74>
<https://github.com/svenhjol/Charm/issues/761>


I’ll leave this report up so others know this isn’t my mod’s fault and how to mitigate the issue.

**Comment by TelepathicGrunt** [comment]
Posting here so others can see. It is some mods have an out dated server translation api inside causing the json reload listeners to no longer fire when with QSL. I talked with a dev and this is what he said. This is the mod he said to download to fix it temporarily 

`But yeah, fix for now is just installing updated Server Translation API:` https://maven.nucleoid.xyz/fr/catcore/server-translations-api/1.4.12%2B1.18.2/server-translations-api-1.4.12%2B1.18.2.jar
![4C37A1B2-3918-4148-A9DA-E6225A03AD2F](https://user-images.githubusercontent.com/40846040/167969510-5a3a9e7d-71e4-4703-b727-e5ae5f6a5b0c.png)
