### ISSUE TITLE
End Shipwrecks not spawning in 4.1.1

### ISSUE THREAD

**Issue by Auzathoth** [TelepathicGrunt/RepurposedStructures-Fabric#192]
I know the changelog for 4.1.1 says "Fixed End Shipwrecks not spawning", but they do not seem to be spawning still. I've checked with a new world, teleporting out into the end. Running a /locate for eg an End Pyramid or an End Mineshaft works, but doing /locate shipwreck_end will basically hang the game/crash a server because it never finds one.

**Comment by TelepathicGrunt** [comment]
fixed now in v4.1.2. Thanks!
