### ISSUE TITLE
Crash at generating a new world

### ISSUE THREAD

**Issue by TheButterbrotMan** [TelepathicGrunt/RepurposedStructures-Fabric#193]
https://bytebin.lucko.me/KSGClshVam

My game is crashing while generating a new world.

**Comment by TelepathicGrunt** [comment]
It is crashing on this line but I do not see how that would be possible. 
https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/blob/e2fefd2d51ebe80ad70659a8e683f2cb22dd3ef9/src/main/java/com/telepathicgrunt/repurposedstructures/misc/maptrades/StructureMapTradesEvents.java#L49

Unless a mod has null trades for their villager profession which is bad. Besides more villagers, what other mods do you have on that have villager professions?

**Comment by TheButterbrotMan** [comment]
I recently updated Dj villagers and Botania.

**Comment by TheButterbrotMan** [comment]
So probably its connected to Dj villagers then.

**Comment by TheButterbrotMan** [comment]
https://github.com/dmkenza/DiscHolder_Fabric

**Comment by TelepathicGrunt** [comment]
Looks like it is discholder. I am able to reproduce the crash. Will see if I can throw in a null check to bypass the issue and let them know to not have null trades (i think)

**Comment by TelepathicGrunt** [comment]
Ok i see the issue. It's 100% my end. DJs have 6 trades. Not 5. So my loop for making a copy was hardcoded to 5 and would crash if it encounters villagers with more than 5 trade tiers. My bad. Fixing now

**Comment by TelepathicGrunt** [comment]
v4.1.5 is out now and should fix this crash!
