### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by WillowMist** [TelepathicGrunt/RepurposedStructures-Fabric#194]
The discord invite in the README file is outdated.  Is there a current Discord link?

**Comment by TelepathicGrunt** [comment]
Oh i didn't think anyone actually reads my github readmes lol. I have been keeping my CurseForge page up to date instead for the general info and links stuff: https://www.curseforge.com/minecraft/mc-mods/repurposed-structures-fabric 

This is the channel link that is active right now: https://discord.gg/K8qRev3yKZ
(Discord Link to ModDevCafe where #telepathicgrunt-mods channel is for my mods)
