### ISSUE TITLE
Nether structures generate within BYG end biomes.

### ISSUE THREAD

**Issue by Stranding14** [TelepathicGrunt/RepurposedStructures-Fabric#195]
Hey there, I'm testing out a few mods together & noticed that nether repurposed structures will generate in BYG end biomes. This is on 1.18.2

Oh the biomes you'll go curse forge link: https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go-fabric

Not sure if these need to be blacklisted within one of the config files or it's another issue, just thought I'd report it in case. 

Images are attached below:

![Example 1](https://user-images.githubusercontent.com/45638686/165449286-1d0b4bb0-c6df-4654-bb62-bb13eb0a86e2.png)

![Example 2](https://user-images.githubusercontent.com/45638686/165449357-b3eb3353-abe1-4458-b48a-474b76927ca1.png)

**Comment by TelepathicGrunt** [comment]
Basically this issue: https://github.com/TelepathicGrunt/RepurposedStructures/issues/198

The short summary is byg has a typo in their c: nether biome tag and accidentally listed their end biomes in there. You’ll have to wait till they update to fix the typo or you can make a datapack to override that tag as a workaround.

https://github.com/AOCAWOL/BYG/blob/1.18.X/Common/src/main/resources/data/c/tags/worldgen/biome/in_nether.json

**Comment by TelepathicGrunt** [comment]
Latest byg is said to have fixed this issue. Please give it a try and let me know if the issue persists.
