### ISSUE TITLE
Failed to create valid structure for repurposed_structures:cities/overworld/start_pool

### ISSUE THREAD

**Issue by Justsnoopy30** [TelepathicGrunt/RepurposedStructures-Fabric#198]
I got this message in the log while walking around. My repurposed structures config is at the defaults.
```
Repurposed Structures: Failed to create valid structure with all required pieces starting from this pool file: repurposed_structures:cities/overworld/start_pool. Required pieces failed to generate the required amount are: [repurposed_structures:cities/overworld/fat_tower_top=2]
  Make sure this structure's size in the config (if it has one) is not set too low.
  Also make sure the max height and min height for this structure in the config (if it has one) is not too close together.
  If min and max height is super close together, the structure's pieces may not be able to fit in the narrow range and spawn.
  Otherwise, if the min and max height ranges aren't close, and structure size isn't super small like 1 or 2, and this message still appears,
  please report the issue to Repurposed Structures's dev with latest.log file!
```

Full log: [latest.log](https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/files/8695742/latest.log)
The last few log lines can be ignored, that was because I updated spark and hadn't restarted the server yet.

**Comment by TelepathicGrunt** [comment]
That message appears when an RS structure with required pieces it must spawn tries over 100 different layouts and could not find one that had the required pieces. I do not know why in this one case, it failed to find a layout with the two large top rooms. 

Unless... the spot it was spawning in was so high that it would've been cut off by world max build height. When that is about to happen, I have the code retry for a new layout instead. So if a city is too high up that it cannot ever fit within build height, I can see this error happening then.

If that's the case, you can safely ignore this message as it is just logging out it could not spawn the structure. Currently, in testing my mod alone, I am able to teleport to and see several Overworld Cities and no errors in the console. I do not see any worldgen json parsing issues in your logs in regards to RS's stuff so I do not think this is a json file that broke in the modpack.

**Comment by TelepathicGrunt** [comment]
Closing as no additional info came up and no one else is reporting the issue
