### ISSUE TITLE
[Error] Failed to get mob

### ISSUE THREAD

**Issue by supersaiyansubtlety** [TelepathicGrunt/RepurposedStructures-Fabric#20]
`Failed to get mob. Please check that repurposed_structures:dungeon_desert.json is correct or that no other mod is interfering with how vanilla reads data folders. Let TelepathicGrunt know about this too!`

[fail_to_get_mob.txt](https://gitlab.com/-/snippets/2004836)
[mod_list-failed_to_get_mob.txt](https://gitlab.com/-/snippets/2004839)

I think all version info and such should be in the log.

**Comment by TelepathicGrunt** [comment]
Ah shoot. not again. Brb lol

**Comment by TelepathicGrunt** [comment]
I uh did != when I should've done ==.
Big brain moment

**Comment by TelepathicGrunt** [comment]
https://www.curseforge.com/minecraft/mc-mods/repurposed-structures-fabric/files/3033449
v1.4.6 should fix the issue and be a good version to leave as the last 1.16.1 version. unless there's a game breaking crash or something lmao.

Thank you for letting me know!

**Comment by supersaiyansubtlety** [comment]
yw, and thanks!
