### ISSUE TITLE
[Feature Request] Way to disable/modify the achievement structure/achievements?

### ISSUE THREAD

**Issue by MaranRoseGIT** [TelepathicGrunt/RepurposedStructures-Fabric#201]
I'm wondering if there is any way to modify the achievements in repurposed-structures, as I have some of the structures disabled and they still are counted in the achievements section, I have players on my SMP who would want to 100% achievement run, and they are confused about why they can not. If there is no possible way currently, can you please add a way to edit such a thing? I hope this isn't a mean feature request or bad to ask, just looking for a way.

_**Minecraft Fabric 1.18.2**_

**Comment by TelepathicGrunt** [comment]
You can disable advancements by datapack. Set their requirements to impossible and hide the advancement.

Example of a datapack I have listed on my mod page for disabling rs advancements. You can delete the files from this datapack for structures you want the advancements to show up for: 
https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/releases/tag/0.0.6

(Note, I may had forgot to include monuments in that datapack)
