### ISSUE TITLE
[Datapack Request] Newest YUNG's Witch Hut

### ISSUE THREAD

**Issue by ardissaps** [TelepathicGrunt/RepurposedStructures-Fabric#204]
https://www.curseforge.com/minecraft/mc-mods/yungs-better-witch-huts-fabric

**Comment by TelepathicGrunt** [comment]
Compat datapacks are on hold until I port all my mods to 1.19 

this request has been added to this issue report that holds all mods to make compat datapacks with: https://github.com/TelepathicGrunt/RepurposedStructures/issues/113

**Comment by TelepathicGrunt** [comment]
Create now: https://www.curseforge.com/minecraft/texture-packs/repurposed-structures-better-witch-huts-compat

**Comment by ardissaps** [comment]
> Create now: https://www.curseforge.com/minecraft/texture-packs/repurposed-structures-better-witch-huts-compat

Thank you very much! :)
