### ISSUE TITLE
"Failed to get mob" errors with "Quilted Fabric API"

### ISSUE THREAD

**Issue by TheSergioEduP** [TelepathicGrunt/RepurposedStructures-Fabric#205]
While using "Quilt Loader" and "Quilted Fabric API" the following error (with different files) gets repeated all the time on the console

```
[20:41:44] [Worker-Main-20/ERROR]: 
***************************************
Failed to get mob. Please check that repurposed_structures:dungeons/deep.json is correct or that no other mod is interfering with how vanilla reads data folders. Let TelepathicGrunt know about this too!
```

This issue does not happen when using "Quilt Loader" and the regular "Fabric API".

(Edited formatting of the code block)

**Comment by TelepathicGrunt** [comment]
Known issue where there’s some other quilt mod causing the json reload listener to no longer fire

https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/issues/191#issuecomment-1124411788

Some users still have issue even with new server translation api so the new offending mods are not yet found.

**Comment by TheSergioEduP** [comment]
Updated server translation api did not work for me, after more testing removing the mod "Charm" also fixed it (while using "Quilted Fabric API"). Where would it be more appropriate to create a bug report/issue?

**Comment by TheSergioEduP** [comment]
Never mind, seems like "Charm" doesn't support Quilt and won't be fixing issues with it.

**Comment by TelepathicGrunt** [comment]
@TheSergioEduP I talked with charm and they were able to make a build that might fix the issue. Can you test with this charm jar and issue if the issue is resolved?
[charm-fabric-1.18.2-4.1.2-TG.zip](https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/files/8883986/charm-fabric-1.18.2-4.1.2-TG.zip)

**Comment by TheSergioEduP** [comment]
@TelepathicGrunt Thanks for your time, that version has fixed the issues that Charm was causing but I have left Quilt for now as it was having some other side effects with other mods.
