### ISSUE TITLE
Cursed WorldGen

### ISSUE THREAD

**Issue by CyberSteve777** [TelepathicGrunt/RepurposedStructures-Fabric#211]
![2022-06-27_01 47 39](https://user-images.githubusercontent.com/69720241/175836863-5be43bab-170f-4ded-be85-9e8922c68079.png)
seed: 7672446156700300351

**Comment by CyberSteve777** [comment]
badland village is above these coords

**Comment by TelepathicGrunt** [comment]
What version of rs are you using? Pretty sure I fixed this a while ago

**Comment by CyberSteve777** [comment]
6.0.7

**Comment by TelepathicGrunt** [comment]
fixed now
