### ISSUE TITLE
Any plan to make Variant of Stoneholm?

### ISSUE THREAD

**Issue by ardissaps** [TelepathicGrunt/RepurposedStructures-Fabric#212]
[Stoneholm](https://www.curseforge.com/minecraft/mc-mods/stoneholm) village with RS variant would be awesome, like when under mesa, the village use red sandstone brick etc, while some with other brick style. Biome dependent.

**Comment by TelepathicGrunt** [comment]
Stoneholm doesn’t change any vanilla structures themselves so it doesn’t fit my mod’s goal with repurposed vanilla structures. I think it would be better for Stoneholm to do the variants themselves and can do it the way they like it best. See if they like the idea!
