### ISSUE TITLE
Cant get mod to work

### ISSUE THREAD

**Issue by gdog637** [TelepathicGrunt/RepurposedStructures-Fabric#217]
i have downloaded all dependencies, downloaded fabric api, and disabled all other mods, and this mod still will not generate the new structures

**Comment by TelepathicGrunt** [comment]
What Mc version? What rs version and dependencies did you download? What is the error you are seeing if any? Server or singleplayer? Does /locate command show any rs structures in autocomplete?

**Comment by gdog637** [comment]
im running on 1.19 fabric using the 1.19 quilt/fabric version of rs. i downloaded the midnightlib mod also, which was the only thing on the dependency page. im receiving no errors, the structures just arent generating. they dont show up when i use /locate and even after flying around for about 5 minutes i only saw vanilla features. also, in singleplayer.i have also tried running in 1.18.2 andim havingthe same issues

**Comment by TelepathicGrunt** [comment]
If you are running fabric, use the Fabric version of RS. Not the Quilt version. Fabric will not run Quilt RS.

this is the latest fabric RS version
https://www.curseforge.com/minecraft/mc-mods/repurposed-structures-fabric/files/3857189

**Comment by gdog637** [comment]
ignore the past message, apparently i managed to accidentally download the quilt version

**Comment by TelepathicGrunt** [comment]
No I’m talking about the file itself and not the project page. My bad on being unclear. That project page contains jars for both fabric and quilt. Is the jar you used called repurposed_structures_fabric-6.1.1+1.19.jar ?

**Comment by gdog637** [comment]
i appreciate the help, thank you
