### ISSUE TITLE
1.18.2 Soul lanterns in Nether strongholds generate waterlogged

### ISSUE THREAD

**Issue by Roadhog360** [TelepathicGrunt/RepurposedStructures-Fabric#219]
![2022-07-15_20 00 02](https://user-images.githubusercontent.com/11903511/179328359-e7006af7-5636-42c7-b77a-94bcaf5d96a3.png)
![2022-07-15_20 00 54](https://user-images.githubusercontent.com/11903511/179328360-d021c272-8141-4fae-b065-13993f930bbb.png)
![2022-07-15_20 00 57](https://user-images.githubusercontent.com/11903511/179328361-7b559da4-f2c2-4303-89aa-16ee908bd362.png)

**Comment by TelepathicGrunt** [comment]
Looks fine to me. Nothing's waterlogged when using RS alone. Sounds like another mod's issue. Just to be sure, this nether stronghold itself is not spawning in water that some other mod added to the nether for some odd reason?

![image](https://user-images.githubusercontent.com/40846040/179337256-d489f604-8ccb-4d1d-9f87-ba4353476deb.png)

**Comment by TelepathicGrunt** [comment]
![image](https://user-images.githubusercontent.com/40846040/179337253-b234d0fe-764c-4cf5-a434-33bc1c6f7b82.png)

**Comment by Roadhog360** [comment]
No. As this seems to be a little less than a one-and-done issue I will attempt to give you more info to debug with. I can give my mods list but as a developer I think it would be far less cumbersome if I zoned into a specific culprit mod, if any.

**Comment by Roadhog360** [comment]
You are right; this does not happen without any other mods. I suspected it was because the lanterns were generating in lava, and waterlogging themselves as they replaced a liquid, but this assumption was wrong. I am going to look at it more tomorrow, for now here's a mod list.

```
additionalbars-3.3.1+1.18.2.jar
Adorn-3.5.0+1.18.2-fabric.jar
AmbientSounds_FABRIC_v5.0.16_mc1.18.2.jar
architectury-4.5.76-fabric.jar
artisanat-2.2.1.jar
badpackets-fabric-0.1.2.jar
bclib-1.4.7.jar
better-end-sky-0.0.1.jar
betterleads-1.0.1+1.18.1.jar
bettermounthud-1.1.4.jar
blockus-2.4.7+1.18.2.jar
'Chimes-1.1.1-1.18.2+[Fabric].jar'
chisel-1.4.5+1.18.x.jar
ciif-1.0.0.jar
cloth-config-6.2.62-fabric.jar
continuity-2.0.0+1.18.2.jar
CreativeCore_FABRIC_v2.6.12_mc1.18.2.jar
customizableelytra-fabric-1.5.3-1.18.jar
dawn-3.3.1.jar
dynamic-fps-2.1.0.jar
DynamicSoundFilters-1.3.0+1.18.2.jar
enderscape-0.3.4-1.18.2.jar
endium-1.1.0-1.18.2.jar
enhancedblockentities-0.7.1+1.18.2.jar
enriched-2.3.0.jar
entityculling-fabric-mc1.18-1.5.1.jar
fabric-api-0.57.0+1.18.2.jar
fabric-language-kotlin-1.8.1+kotlin.1.7.0.jar
fabric-seasons-1.4-BETA+1.18.jar
fallingleaves-1.11.1+1.18.2.jar
Fastload-1.1.5.jar
feature_nbt_deadlock_be_gone_fabric-2.0.0+1.18.2-rc1.jar
ferritecore-4.2.1-fabric.jar
friendsandfoes-fabric-mc1.18.2-1.4.5.jar
here-be-no-dragons-1.0.0.jar
indium-1.0.6+mc1.18.2.jar
infinityfix-1.0.0.jar
iris-mc1.18.2-1.2.5.jar
IronChests-1.7.2.jar
item-model-fix-1.0.3+1.18.jar
krypton-0.1.9.jar
lambdynamiclights-2.1.0+1.17.jar
lanterns-belong-on-walls-1.2.0.jar
lazydfu-0.1.2.jar
leaves-us-in-peace-1.0.5+MC1.18-1.18.2.jar
lithium-fabric-mc1.18.2-0.7.10.jar
MissingWIlds-fabric-1.18.2-1.1.0.jar
modmenu-3.2.3.jar
moreculling-1.18.2-0.2.0-alpha.jar
mostructures-1.4.2+1.18.2.jar
NaturesCompass-1.18.2-2.0.3-fabric.jar
netheritebeacons-1.2.0.jar
profundis-1.3.0.jar
promenade-2.6.3.jar
puzzle-1.3.4-1.18.jar
reeses_sodium_options-1.4.3+mc1.18.2-build.42.jar
repurposed_structures_fabric-4.1.14+1.18.2.jar
RoughlyEnoughItems-8.3.502.jar
smoothboot-fabric-1.18.2-1.7.0.jar
snowy-trees-1.1.0.jar
sodium-fabric-mc1.18.2-0.4.1+build.15.jar
starlight-1.0.2+fabric.89b8d9f.jar
TerraBlender-fabric-1.18.2-1.1.0.102.jar
terrarian-slimes-1.2.1-BETA+1.18.jar
tooltiptweaks-1.0.jar
traverse-5.1.0.jar
twigs-fabric-1.1.3-patch2+1.18.2.jar
variantcraftingables-2.4.jar
vmp-fabric-mc1.18.2-0.2.0+beta.3.17-all.jar
world-of-food-1.1.1+1.18.x.jar
wraith-waystones-2.5.5+mc1.18.2.jar
wthit-fabric-4.11.0.jar
```

**Comment by TelepathicGrunt** [comment]
It's been a week, thought I'll pop in and ask if you found what mod was waterlogging the lanterns? Just so I know what to look for if someone else reports the same issue

**Comment by Roadhog360** [comment]
No sorry, I got sidetracked.

**Comment by TelepathicGrunt** [comment]
That's alright, no rush tho. I'll keep this up to see if anyone else can chime in

**Comment by TelepathicGrunt** [comment]
Going to close this as it has been 13 days with no response and we already ruled my mod out as a cause.
