### ISSUE TITLE
 Couldn't parse spawner mob list repurposed_structures:dungeon_desert and for bunch of other structures

### ISSUE THREAD

**Issue by jaanjicm** [TelepathicGrunt/RepurposedStructures-Fabric#22]
https://paste.ubuntu.com/p/N2nZzb5bhx/

I can't copy more than 2 for some reason, but there is 68 of them

**Comment by TelepathicGrunt** [comment]
This was resolved in v1.4.6 Repurposed Structures for 1.16.1. Please update Repurposed Structures to the latest version for the MC version you’re on. :) 

If you’re actually using v1.5.0 on 1.16.2 and gotten this error, please let me know and upload the latest.log file for me to see (can be found in the log folder that is in the .minecraft folder). I’ll reopen the issue if that’s the case
