### ISSUE TITLE
RS not working for Fabric 1.19.2 (No Quilt, only Fabric API and Fabric)

### ISSUE THREAD

**Issue by TheOldMan03** [TelepathicGrunt/RepurposedStructures-Fabric#225]

**Comment by TelepathicGrunt** [comment]
Did you make sure to grab the fabric version of RS instead of the quilt version? Fabric will not load the quilt RS jar.

fabric RS jar: https://www.curseforge.com/minecraft/mc-mods/repurposed-structures-fabric/files/3857189

If that does not work, please give me latest.log file and a picture of your mods folder with the rs jar inside

**Comment by jga-03** [comment]
How do I acquire the latest.log file?

**Comment by TheOldMan03** [comment]
![notwork](https://user-images.githubusercontent.com/103955893/189702896-d6f2f1ce-76d9-4b95-b98b-b5d31c4ee69d.png)
[latest.log](https://github.com/TelepathicGrunt/RepurposedStructures-Quilt/files/9549822/latest.log)

**Comment by TelepathicGrunt** [comment]
This doesn’t look like a rs issue. You ran out of memory when the game was loading terralith’s structures. If that stops the game from loading rs structure files as well, then rs pieces won’t spawn too. 
![EEA5E9A6-059D-4D04-8439-59C91D4F8F9B](https://user-images.githubusercontent.com/40846040/189706402-342c1531-cd93-4401-94ef-40a90cddf2e8.png)


Increase the amount of RAM being used. Also, I would encourage not using Optifine on Fabric as it causes issues with too many fabric mods. There are many fabric Optifine alternative you can explore instead 

https://lambdaurora.dev/optifine_alternatives/

**Comment by TheOldMan03** [comment]
I have increased the RAM usage to 4GB, but the RS mod doesn't seem to work either 
[latest.log](https://github.com/TelepathicGrunt/RepurposedStructures-Quilt/files/9550121/latest.log)

I have also removed removed Optifine and added Sodium Instead

**Comment by TheOldMan03** [comment]
Nvm The advancements have popped up for the RS mod, is the Jungle Pyramid still the default Minecraft Structure or is there any change to that?

**Comment by TelepathicGrunt** [comment]
RS does not change vanilla structures. It only adds new variants of vanilla structures to other biomes/dimensions. 

I loaded up Fabric RS 6.1.1 and it works for me. I am able to use locate command to find RS structures and teleport to them to see them spawned.
![image](https://user-images.githubusercontent.com/40846040/189717891-8641815c-625a-4deb-b107-4323f3262172.png)

**Comment by TheOldMan03** [comment]
Ok Then the issue is resolved, Thank you so much
