### ISSUE TITLE
Request a new version

### ISSUE THREAD

**Issue by SadEPa0628** [TelepathicGrunt/RepurposedStructures-Fabric#227]
Please quickly update the version for 1.20.2, I really like this mod

 <font size=2>The content is translated from Chinese. Please understand if there are any mistakes</font>

**Comment by SadEPa0628** [comment]
emm...MD wrong

**Comment by SadEPa0628** [comment]
Uh, that still doesn't seem right

**Comment by SadEPa0628** [comment]
Well, you know, I want that in fine print. The content is translated from Chinese. Please understand if there are any mistakes...

**Comment by SadEPa0628** [comment]
Well, there does seem to be a mistake in the translation, if you understand

**Comment by SadEPa0628** [comment]
Oh, my God, this translation is so wrong...

**Comment by SadEPa0628** [comment]
ah)(*&&#$)^%*&Q%(&^*

**Comment by TelepathicGrunt** [comment]
When Neoforge is out for 1.20.2, then I will begin updating all my mods for 1.20.2. It requires work to update. It is not a simple button press to update a mod

**Comment by SadEPa0628** [comment]
OK
