### ISSUE TITLE
Structures stick out of the Nether ceiling, thus allowing access to top of bedrock level.

### ISSUE THREAD

**Issue by vini2003** [TelepathicGrunt/RepurposedStructures-Fabric#24]

**Comment by TelepathicGrunt** [comment]
Which structures? The nether structure I used have a maximum Y height set that I thought already prevents them from being too high

**Comment by TelepathicGrunt** [comment]
It's nether well. Will lower it from 127 to 117 for next update

**Comment by TelepathicGrunt** [comment]
fixed in 1.5.2 which is now released. :)
Thank you for reporting this bug!
