### ISSUE TITLE
Nether Overworld?

### ISSUE THREAD

**Issue by Afrocntrik** [TelepathicGrunt/RepurposedStructures-Fabric#27]
![2020-09-02_03 03 01](https://user-images.githubusercontent.com/11052983/91942838-93c58b00-ecc9-11ea-832a-0f6f8a3df99b.png)
![2020-09-02_02 59 56](https://user-images.githubusercontent.com/11052983/91942849-96c07b80-ecc9-11ea-8ca2-e2aa0314f0de.png)

**Comment by TelepathicGrunt** [comment]
This looks pretty much 100% another mod's issue. All repurposed structure does is add structures/features so land changing the blocks used is definitely an issue with some other worldgen mod. Try removing mods and see if you can find which one is generating the grass.

**Comment by Afrocntrik** [comment]
Okay thanks, I'll keep you updated then since it's either BYG or Allure

**Comment by Afrocntrik** [comment]
You're not going to believe this but the nether is trying to emulate the Bumblezone's terrain generation same mod list as my other [issue](https://github.com/TelepathicGrunt/Bumblezone-Fabric/issues/12), I can tell by how the water spawns and the wall generation
![2020-09-02_14 56 45](https://user-images.githubusercontent.com/11052983/92024945-da989c80-ed2c-11ea-96d6-eb5899a09a44.png)
![2020-09-02_15 03 19](https://user-images.githubusercontent.com/11052983/92025452-8a6e0a00-ed2d-11ea-8a78-d776e221178c.png)
![2020-09-02_15 03 42](https://user-images.githubusercontent.com/11052983/92025487-9a85e980-ed2d-11ea-932f-8c5affb2d678.png)
