### ISSUE TITLE
"Failed to get mob" errors

### ISSUE THREAD

**Issue by BrekiTomasson** [TelepathicGrunt/RepurposedStructures-Fabric#30]
I saw the same error reported in #22 - but I've double-checked that I am, in fact, running Repurposed Structures 1.4.6 under Minecraft 1.16.1, so there shouldn't be any conflicts there. I suspect this is a conflict with some other mod as I have recently been rebuilding my mod library, but I haven't touched Repurposed Structures. Here's an excerpt of my latest.log up until the first instance of the error:

As I continue to move around the world, the error repeats itself for other JSON files, such as repurposed_structures:dungeon_ocean_neutral.json when I get close enough to the ocean for it to begin generating those chunks, etc.

[latest.log](https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/files/5250880/latest.log)

**Comment by TelepathicGrunt** [comment]
I really hate to say this but the 1.16.1 version of my mod is no longer supported as I do not have the time to work on and bugfix multiple versions of my mods. Though if you can narrow down which other mod is breaking the reading of the json files, that would really help as that mod could be causing issues with AoF too on 1.16.3. I'm seeing issues with modpacks were some unknown mod is breaking the reading of json/nbt files somehow. Would be nice to find who it is.

If I recall, 1.4.6 is using the same exact dungeon code and json stuff as the 1.5+versions but I haven't heard of this dungeon issue for latest which is odd.

**Comment by BrekiTomasson** [comment]
I managed to resolve it by removing the configuration file and letting the mod regenerate it. I must have snuck in something buggy when tweaking the settings the other day, but can't imagine what it would have been for this particular error to pop up. I'm no longer getting the same error, but I'll let you know if it pops up again after doing some more tests to see what the underlying conflict might be.

Thanks for your quick answer, and best wishes for the future of this mod!

**Comment by TelepathicGrunt** [comment]
Oh thank you for letting me know! That is super strange the config file was the issue. I'll keep that in mind for similar reports in the future!
