### ISSUE TITLE
(forge version) Ocean Dungeon BIG LAG

### ISSUE THREAD

**Issue by Marshmalllow09** [TelepathicGrunt/RepurposedStructures-Fabric#35]
Looks like with every chunk load, new or existing, it tries to generate an ocean dungeon.
[11Oct2020 18:40:58.000] [Worker-Main-42/ERROR] [com.telepathicgrunt.repurposedstructures.world.features.DungeonOcean/]: What in the world? The Ocean Dungeon attempted to spawn in a biome not registered in both the DynamicRegistries or WorldGenRegistries.
Please tell TelepathicGrunt (RepurposedStructures dev) this and tell him your mod list you have on.
For now, Ocean Dungeons will use repurposed_structrues:dungeon_ocean_misc mobs as fallback.

Using All the mods 6

**Comment by TelepathicGrunt** [comment]
FYI, you're on the fabric github for repurposed structures lol. But that's alright 

Anyway what version of blame are you using? The latest is 1.4.3 and last time I tried it with repurposed structures, it didn't report anything as the features are registered (blame had a glitch before in older versions where it didn't detect registered stuff correctly)

Also, what make you certain it is the ocean dungeon? Once a chunk is generate, it's impossible for the dungeon to attempt to generate in it. But for all new ocean chunks, it should attempt something like 6 times to find a suitable place to spawn a dungeon as the chunk is being made.

**Comment by TelepathicGrunt** [comment]
oh i misread sorry

**Comment by TelepathicGrunt** [comment]
Ok so let see, i thought this was a log report from another one of my mod called Blame lmao.

so there something really strange going on here. The ocean dungeon attempted to spawn but the biome it was in is not in any of the registeries which is... bad. Yeah can you put on Blame and then post the full Latest.log file? Something wack is going on.

(also, make sure you are not using optifine as it break biome mods right now)

**Comment by Marshmalllow09** [comment]
Seems the AllTheMods 6 downloads an old version of repurposed structures.
Downloaded the newest one, server crashed, rrealized it downloaded an old
version somehow. Downloaded the new New update, and I'm not getting the
error anymore. But there is still lag with chunk loading. So problem
solved, kinda. It's not unplayable lag now though

**Comment by TelepathicGrunt** [comment]
Huh. Well at least the error is gone! I'll close this then but you should let ATM6 know about the lag so they can try and see if they can figure out what is lagging. 

But thank you for at least reporting this! :)
