### ISSUE TITLE
How do I disable achievements?

### ISSUE THREAD

**Issue by Romz24** [TelepathicGrunt/RepurposedStructures-Fabric#37]
I am using the mod only on the server side, because of this, the names of the achievements are not displayed correctly.

![image](https://user-images.githubusercontent.com/2458113/96353086-96d9d680-10d1-11eb-9b8e-49675cea20d2.png)
![image](https://user-images.githubusercontent.com/2458113/96353095-a48f5c00-10d1-11eb-8848-2913fbbc242d.png)

**Comment by TelepathicGrunt** [comment]
There's two things you can do. You can either have the players up on a resource pack that uses repurposed_structure's en_us.json file to do the translations. Or you can use a datapack to disable the advancements completely. 

here's the datapack. All I did was take the hidden advancement datapack at bottom of my curseforge mod page and changed the trigger entry to "minecraft:impossible" for all the advancements. Now they are impossible to trigger without commands. Hope this helps!
https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/releases/download/0.0.6/Repurposed_Structures-Disabled_Advancements.zip
