### ISSUE TITLE
Giant boulders cover the landscape

### ISSUE THREAD

**Issue by magneticflux-** [TelepathicGrunt/RepurposedStructures-Fabric#41]
From my issue https://github.com/franiscoder/mostructures/issues/12.

After experimentation, I suggest `giantBouldersPerChunk = 0.1` as a default instead of `giantBouldersPerChunk = 1.0`. It adds occasional boulders, but doesn't cover the landscape entirely.

**Comment by TelepathicGrunt** [comment]
I was actually going for something like this image of plentiful giant boulders to work your way around. I could lower the spawn rate a bit but i feel like the boulders being rare/occasional kind of ruins what I was going for. Though that is why this is a config option so players can tune it to exactly what they want!
![3254D93D-DA82-4EC9-A9C9-A66C0E6BC916](https://user-images.githubusercontent.com/40846040/97173800-87106100-1767-11eb-9450-20cbcac9c56d.jpeg)

**Comment by TelepathicGrunt** [comment]
v1.6.9 now has boulders be more varied in size (the size you saw and can be smaller) and now has the config rate set to 0.5. Both these changes should make the boulders look nicer for default config settings hopefully
