### ISSUE TITLE
Unknown mod breaking structure processor files

### ISSUE THREAD

**Issue by MechanosG** [TelepathicGrunt/RepurposedStructures-Fabric#46]
While investigating the source of some mysterious lag I get when I go underground, I noticed a ton of error spam in my log.  There was no indication what mod was causing the error spam, and I only got lucky by searching snippets of the output in github, which led me to here.  The first error line in the log says this:

> [20:45:28] [main/ERROR]: Error loading registry data: Not a json array: {"processors":[{"rules":[{"output_state":{"Name":"minecraft:nether_wart_block"},"input_predicate":{"block":"minecraft:crimson_hyphae","probability":0.02,"predicate_type":"minecraft:random_block_match"},"location_predicate":{"predicate_type":"minecraft:always_true"}},{"output_state":{"Properties":{"axis":"x"},"Name":"minecraft:crimson_hyphae"},"input_predicate":{"block":"minecraft:crimson_hyphae","probability":0.3,"predicate_type":"minecraft:random_block_match"},"location_predicate":{"predicate_type":"minecraft:always_true"}},{"output_state":{"Properties":{"axis":"y"},"Name":"minecraft:crimson_hyphae"},"input_predicate":{"block":"minecraft:crimson_hyphae","probability":0.4,"predicate_type":"minecraft:random_block_match"},"location_predicate":{"predicate_type":"minecraft:always_true"}},{"output_state":{"Properties":{"axis":"z"},"Name":"minecraft:crimson_hyphae"},"input_predicate":{"block":"minecraft:crimson_hyphae","probability":0.5,"predicate_type":"minecraft:random_block_match"},"location_predicate":{"predicate_type":"minecraft:always_true"}},{"output_state":{"Name":"minecraft:nether_wart_block"},"input_predicate":{"block":"minecraft:crimson_nylium","probability":0.15,"predicate_type":"minecraft:random_block_match"},"location_predicate":{"predicate_type":"minecraft:always_true"}},{"output_state":{"Properties":{"axis":"y"},"Name":"minecraft:crimson_hyphae"},"input_predicate":{"block":"minecraft:crimson_stem","probability":0.22,"predicate_type":"minecraft:random_block_match"},"location_predicate":{"predicate_type":"minecraft:always_true"}}],"processor_type":"minecraft:rule"}]}

Then it's proceeded by many man other similar lines starting with:
> [20:45:28] [main/ERROR]: Pool element: Not a json array: {"processors":[{"rules":[{"output_state":{"Name":"minecraft:cracked_polished_blackstone_bricks"},"input_predicate":{"block":"minecraft:blackstone","probability":0.1,"predicate_type":"minecraft:random_block_match"},

Then continuing for the entire json entry.  There's no actual crashes or info citing specific mods.  Just so much spam in the log that it quickly got over 1MB in size with-in a minute and a whole lot of lag, although I haven't confirmed the lag is actually caused by this.  The lag _could_ be something else (probably), so I'll test without this mod next to see what happens.

MC 1.16.3
Fabric 0.6.1.51
repurposed_structures-1.16.3-1.6.9
About 130 other mods

**Comment by TelepathicGrunt** [comment]
Do you have Trees Do Not Float or Immersive Portals on or an outdated version of Better Slabs?

The error you see there is when a mod is either trying to create a new Dynamic Registry from scratch (which they shouldn't) or they added properties to block in an unsafe manner that breaks vanilla's ability to parse structure processor files. (which then causes structures unable to spawn)

The lag can be from excessive spam but I have not seen it happen where the above problem was non-stop. Usually it only prints at world load and that's it. If you can get me all the mods you are using, I can start cutting it in half and try to narrow down the mod that's breaking mine

**Comment by MechanosG** [comment]
I have Trees Do Not Float yes.  I don't have Immersive Portals or Better Slabs (but I do have a similar discontinued slab mod I'll be removing).  My mod list is fairly large so this will take some typing (idk how to export a list of mods).  I'm going by the jar names, so if a name seems a little off, that'd be why.

Age Of Exile 1.7.6
Allure 1.2.7
amecs 1.3.2
Appleskin Fabric 1.0.11
Artifacts Fabric 1.0.0
autoconfig1u 3.3.1
Automated Crafting 1.3.11
Balance of Exile 1.0.3
Bedrockify 0.1.8
(YUNG's) Better Caves 1.0.3
Better Dropped Items 1.2.2
Better Eating Mod 0.2.0
Better End 0.5.2
Better Graves 0.4.1
Better Nether 4.1.8
Better Stones 0.0.4
Biome Makeover 1.0.2
Blockus 1.6.5
Break Progress 1.0.0
Builder's Blocks beta.9
Companion 1.2.0 build.39
Can I Mine This Block 1.0.2
Canvas 1.0.989
Cardinal Components API 2.7.2
CC Tweaked Fabric 1.91.2
Cinderscapes 1.2.3 build.37
Cleancut Fabric 2.1
Clearview 2.1
Clickthrough Fabric 0.17.2-0.3
Colormatic 2.2.7
Cloth Config API Fabric 2-4.8.2
Convenient Mobgriefing 1.1.3
Creeper Spores 1.4.1
Croptopia 1.0.3
Crowmap 1.0.1
Curios Fabric 0.0.10
Custom Spawn 0.1.2
DamageTilt Fabric 0.1.0
Dankstorage 1.8c
Dark Loading Screen 1.5.0
Darkness 1.6.50
Demeter 2.0.0
Direbats Fabric 1.0.0
Disable Custom World's Advice Fabric 1.1
Don't Drop It 2.1.0
Dungeon of Exile 1.1.1
Easier Crafting Fabric 0.17.2-1.6.5
Edit Sign Fabric 2.1.3
Expanded Storage 5.6.30
Fabric API 0.25.0 build.415
Fabric language Kotlin 1.4.0 build.1
Fastbench 2.3
Fastfurnace 2.3
Glassdoor 1.5.0
Glowing Beds 1.2.1
Gotta Climb Fast 1.0
Gunpowder Base 0.2.10 (just realized I may not need this for sleepvote to work)
Gunpowder Sleepvote 1.0.1
Simple Harvest 1.2.12-26 (just realized this could have issues so imma replace it with tiny tweaks)
Hwyla Fabric 1.9.23-79
I Am Very Smart Fabric 2.1.0
Illuminations 1.2.3
Industrial Revolution 1.7.2 Beta
Inmis 1.3.0
Inventory Tabs 0.2.3
Jumploader 2.0.1
Justmap 1.2.13
LambDynamicLights 1.3.1
Lapis Reserve 1.0.6
Library Of Exile 1.0.6
Linked Storage 1.3.11
Lithium 0.5.6
Mambience 2.1.0
Materialisation 3.0.3
Megane 2.1.0
Mobs Attempt Parkour 0.2.1
Modern Industrialization 0.3.3
ModMenu 1.14.6 build.31
Mo Glass 1.4
Monster of the Ocean Depths 2.6
More Berries 1.3.3
Muffle 0.1.1
Not Enough Crashes 2.1.4
Nourish 1.1.1
Ok Zoomer 4.0.1
Patchouli 1.16.2
Phosphor 0.6.0 build.7
Pling 1.2.0
Presence Footsteps r28
RebornCore 4.5.0 build.84
Repurposed Structures 1.6.9
Roughly Enough Resources 2.1.2
Respawnable Pets 1
Roughly Enough Items 5.7.1
Shield Disruptor 1.1.1
Simple Drawers 1.8.0
Slotlink 2.0.2
Smoke Extender 1.4.0
Smoothboot 1.0.0
Strong and Fair Anvils 0.3.0
Taco Bell Fabric 1.1.0 (lol)
TCrafting 1.2.1
Trees Do Not Float 1.12.97
Tech Reborn 3.6.1 build.143
Terrestria 2.1.4
TIS-3D Fabric 1.5.0.10
UnforgivingVoid 2.0.0
Vertical Slabs 1.0.3 (going to remove this)
Wooden Hoppers 1.0.0

**Comment by TelepathicGrunt** [comment]
Can you try making a world without trees dont float? It is known already that they conflict with repurposed structures https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/issues/36
I did make an issue report to them so hopefully they can patch the issue with the processors failing. but it wouldn't explain the lag hmm

**Comment by MechanosG** [comment]
I could probably do that.  Also as far as lag goes, I've noticed some new things.  Just Map has a couple issues I discovered, one related to missing mob head icons (fixed by turning off head icons), one related to caving that activates when I try to submerge in water or travel down narrow holes (turning off 'show caves' made that particular lag go away).  Both were happening at the same time as the repurposed structure errors, so it's responsible for at least some of the lag.  Now that I've eliminated those, if I recreate that world seed without trees don't float, I should get a better idea of what's happening.

Speaking of lag, I temporarily disabled repurposed structures, and turns out that was a bad idea.  The world constantly kept trying to make repurposed structures, then spammed errors involving ocean mineshafts that no longer existed, and it would create a lag spikes every time it tried.  This spammed the log quite a bit, even when staying in one area.  So I tested recreating the world with the exact same seed, and that fixed it.  So apparently removing repurposed structures nukes existing worlds as the registered structures don't clear out of the save.

**Comment by TelepathicGrunt** [comment]
Yeah dont remove structure mods. It's caused by a vanilla bug https://bugs.mojang.com/browse/MC-194811

Although Fabric API should have patched the bug to prevent it from happening. strange

**Comment by MechanosG** [comment]
I enabled repurposed structures, disabled trees do not float, and recreated the world I was using for testing.  Still getting the the same console errors.  There's absolutely no lag though now, not counting the log window (it's struggling when I scroll up and down).  In fact I'm getting..  oddly high FPS in game, which has left me scratching my head.

**Comment by TelepathicGrunt** [comment]
Well, the removal of TDNF will solve a lot of the nether log block processors failing but "minecraft:cracked_polished_blackstone_bricks" would still break as TDNF doesnt mess with that block. I tried a few mods from the list but no luck. If you can zip up all the mods and send it to me, I can easily try the reproduce the issue instead of having to download every mod individually (which is super slow for me oof). Not sure which mod is adding properties to blackstone blocks

**Comment by TelepathicGrunt** [comment]
Any news on this? Though, TDNF did push an update that solves their incompat with my mod.

**Comment by TelepathicGrunt** [comment]
Gonna close this due to inactivity now. I'll keep an eye out on if anyone else reports the same issue
