### ISSUE TITLE
pyramid_nether blows up when the chest is opened but there is no way to prevent this.

### ISSUE THREAD

**Issue by RDKRACZ** [TelepathicGrunt/RepurposedStructures-Fabric#54]
There is no TNT under the chest - how this blows up in that case?

**Comment by TelepathicGrunt** [comment]
There is TNT under the chest lol. Trapped Chests can put Redstone power through the solid block that it rests upon. Below that solid block is the TNT. Simply dig deeper below the chest to find the TNT and remove it prior to opening the chest.
