### ISSUE TITLE
My dog's collar changes back to red every time I leave and join the game.

### ISSUE THREAD

**Issue by DeropManz** [TelepathicGrunt/RepurposedStructures-Fabric#55]
I've singled every other mod in my fabric mod pack and I've come to the conclusion it's this mod.

**Comment by TelepathicGrunt** [comment]
Errr. You're gonna have to be a lot more specific than that as this a structure mod that doesn't touch rendering at all or dogs or mobs lmao.

Can I have your mod pack to test for sure? How are your changing the dog collars?

**Comment by TelepathicGrunt** [comment]
what the f. Did testing and yeah it is a reproducible issue using nothing but fabric api and latest repurposed structures. How in the actual legitimate heck does this even happen??? Is there a bug in one of my dependencies?

**Comment by DeropManz** [comment]
Lol, I was thinking along these lines as well while searching for the cause, like how could it be the structure mod of all things? But besides this small bug, this is a pretty good mod. 10/10 would eat again.

**Comment by TelepathicGrunt** [comment]
Found the issue. It's caused by a mixin in Angerable Patch that is bugged. Once that mod updates to fix the issue, I'll release a new version of repurposed structures with the fixed dependency. 
https://github.com/Draylar/angerable-patch

**Comment by DeropManz** [comment]
Would it still be safe if I name my dog?

**Comment by TelepathicGrunt** [comment]
nametags still work and save properly so yes, that should be safe

**Comment by TelepathicGrunt** [comment]
angerable patch updated and I just released a new version of my mod with the updated dependency. Dog collar color should save properly now!

**Comment by DeropManz** [comment]
Pog
