### ISSUE TITLE
Modded biomes option not working?

### ISSUE THREAD

**Issue by connorgoober** [TelepathicGrunt/RepurposedStructures-Fabric#6]
Maybe this is just bad luck, but after extensive searching via the locate command across thousands of blocks I cant find any of these structures in modded biomes. The option is set to true yet every structure i have found has only been in vanilla biomes.

**Comment by TelepathicGrunt** [comment]
Which mod were you using and did you restart the game after you turned on the add___ToModdedBiomes option?

**Comment by connorgoober** [comment]
I was using oh the biomes you'll go. I did restart after turning it on.

**Comment by TelepathicGrunt** [comment]
Oh the commit feature auto closes the issue. Huh.

Anyway, Thank you for reporting this bug! This has been fixed in v1.1.0 which should be approved shortly on curseforge :)
https://www.curseforge.com/minecraft/mc-mods/repurposed-structures-fabric
