### ISSUE TITLE
Overworld outposts do not spawn pillagers over time

### ISSUE THREAD

**Issue by TelepathicGrunt** [TelepathicGrunt/RepurposedStructures-Fabric#68]
Make the forge version use the forge mob hook too so it has better mod compat. (Pass in list of mobs in constructor to use for structure spawning)

**Comment by TechniumUnlimited** [comment]
Does this affect only outposts created by this mod or, all outposts?

**Comment by TelepathicGrunt** [comment]
only outposts from RS. Basically, in code, structures have a list of mobs they can spawn over time. For RS's structures, I forgot to add the list. Other mods and vanilla's outposts will have the list as they added it to their structures

**Comment by TechniumUnlimited** [comment]
np, I have disabled generation of the outposts from this mod for now.

**Comment by TelepathicGrunt** [comment]
Fixed in v2.3.4 Forge and 1.7.4 Fabric!

Forge: https://www.curseforge.com/minecraft/mc-mods/repurposed-structures/files/3169638
Fabric: https://www.curseforge.com/minecraft/mc-mods/repurposed-structures-fabric/files/3169629
