### ISSUE TITLE
Create datapack to add Charm/Strange houses to RS's villages 

### ISSUE THREAD

**Issue by TelepathicGrunt** [TelepathicGrunt/RepurposedStructures-Fabric#70]
Special thanks to ridjack for letting me know this was a thing in Charm and Strange! I didn't know lol. Ok so, it seems Charm/Strange is hardcoded to vanilla villages. A datapack to add their houses to rs villages would help people. Although, this means the wood type or house style might not match. Maybe make new variants of their builds too? 

Definitely on the backburner until I get more time and fix the other bugs.

Charm and Strange nbt files:
https://github.com/svenhjol/Charm/tree/0b87e3bf00698fbcadbbe54419dce504436fa52c/src/main/resources/data/charm/structures/village
https://github.com/svenhjol/Strange/tree/1.16-fabric/src/main/resources/data/strange/structures/village

**Comment by Coranthes** [comment]
I would be happy to get you the nbt's for all the builds but... they have heavy data block usage with custom code throughout, so I'm not sure if you want that.  I'm actually going to be making some slight changes to them, probably tomorrow, but I'm happy to get you whatever you need.   There are future plans for some of our village builds, but that may be a long way off yet.  Between svenhjol's projects I keep pretty busy. But just let me know if you need anything, I'm happy to help.

**Comment by TelepathicGrunt** [comment]
Thank you! I was just gonna download the nbt files off of the github, look at a few of them spawned by Structure Block, then use a script to swap blocks for others like Oak Logs for Birch Logs and stuff. Then just ship the new nbt files in the datapack with it overriding my structure pools to have the structure piece. It looks like the houses charm adds is using vanilla's MOSSIFY_10_PERCENT processor, legacy piece type, and rigid. How are the data blocks parsed in the structure piece if it is not using a custom processor?

And no need to rush with updating them. I'm currently tied up with porting another one of my mods so it be a bit before I get around to fixing all the bugs in RS and adding more mod compat stuff. Just let me know when charm and/or strange piece's are at a stable place for me to start doing compat.

**Comment by Coranthes** [comment]
Ok sounds good.  I know I have a ton to do personally.   I do all his textures and have been picking up some code here and there.  In response to your question, I'll just post a screenshot of what he had to say. 
![image](https://user-images.githubusercontent.com/64534930/103488768-905c2080-4ddd-11eb-91d2-797f5ea086b0.png)

**Comment by TelepathicGrunt** [comment]
Just popping in to say I may start making the datapack compat for both the fabric and forge version soon. You mentioned about having plans on adjusting some of Charm's houses. Will that be happening very soon or should I just go ahead and add the house compat?

**Comment by TelepathicGrunt** [comment]
Repurposed Structures 1.17 release now has the charm compat datapack listed on the modpage! It works in my tests so it should be good for use now
