### ISSUE TITLE
Trapdoor placed backwards in nether brick shipwreck

### ISSUE THREAD

**Issue by FewerFlaws** [TelepathicGrunt/RepurposedStructures-Fabric#71]
Clearly the center one should match the others =]

![2021-01-07_13 25 48](https://user-images.githubusercontent.com/75643699/103946923-2a78dd00-50ec-11eb-816a-57dda973a0e9.png)

**Comment by TelepathicGrunt** [comment]
Good catch!

**Comment by TelepathicGrunt** [comment]
Fixed in v2.3.4 Forge and 1.7.4 Fabric!

Forge: https://www.curseforge.com/minecraft/mc-mods/repurposed-structures/files/3169638
Fabric: https://www.curseforge.com/minecraft/mc-mods/repurposed-structures-fabric/files/3169629

Thank you for reporting this issue!

**Comment by FewerFlaws** [comment]
You got it, boi <3
