### ISSUE TITLE
[Feature request] Ice pyramid.

### ISSUE THREAD

**Issue by RDKRACZ** [TelepathicGrunt/RepurposedStructures-Fabric#74]
What about something like this?
![image](https://user-images.githubusercontent.com/43277609/107144907-88dce980-693e-11eb-8afb-39d45db82ade.png)
Yep, It's pewdiepie's video...

**Comment by TelepathicGrunt** [comment]
i'll be honest, i dont like the block choices for that pyramid lol. I would use snow blocks as the main block instead. I'll play around with it and see if I can make it look good

**Comment by TelepathicGrunt** [comment]
![2021-02-16_10 02 48](https://user-images.githubusercontent.com/40846040/108278869-b0eff800-7149-11eb-8d91-5fa55e50b276.png)
Added snowy pyramid in v1.8.0 which is now released!
