### ISSUE TITLE
End Mineshafts generate in the void.

### ISSUE THREAD

**Issue by RDKRACZ** [TelepathicGrunt/RepurposedStructures-Fabric#75]
Maybe it's an incompatibility with BetterEnd mod. I'm not sure yet, will test.
![2021-01-31_03 41 24](https://user-images.githubusercontent.com/43277609/107145074-9e9ede80-693f-11eb-9ae2-44da260f0279.png)

**Comment by TelepathicGrunt** [comment]
Looks fine to me if barrensIslandsEndMineshafts is set to true in the configs. set that to off to make the mineshafts not float outside islands

**Comment by TelepathicGrunt** [comment]
just reach out, was the config indeed the issue?

**Comment by TelepathicGrunt** [comment]
closing this report due to no follow up so I'm gonna assume the config suggestion fixed this lol
