### ISSUE TITLE
Suggestion: Ender mines in small island biome option

### ISSUE THREAD

**Issue by TimelapsedEon** [TelepathicGrunt/RepurposedStructures-Fabric#8]
Can we get a config option for whether we want the mines to spawn in the small island biome? I tested the build just before they were removed and I really liked them just hanging in air like they were needed over the void.

**Comment by TelepathicGrunt** [comment]
They are in the End Midlands and End Highland biomes and could be large enough to enter the void space. But a config isn't a bad Idea. I'll try and add one! It funny how when they were in the end isaldn biome (which was a glitch), I had people not liking that lol.

**Comment by TimelapsedEon** [comment]
I mean, fair. I just happened to like how it breaks up the consistent void.

**Comment by TelepathicGrunt** [comment]
1.2.0 is now out with the config for end mineshafts to spawn in any end biome! 
Let me know if any issues comes up with it!
