### ISSUE TITLE
Ocean Dungeons spawns in Terrestria's Lush Deserts

### ISSUE THREAD

**Issue by IdrisQe** [TelepathicGrunt/RepurposedStructures-Fabric#86]
I have no idea if this is an issue between Repurposed Structures and Terrestria, or if it has to do with me using Overworld Two's terrain generator, but I just found a completely dry Ocean Dungeon in the middle of a Lush Desert, complete with Drowned Spawner.
![2021-02-28_18 52 38](https://user-images.githubusercontent.com/40530630/109447522-ba564b80-79f8-11eb-9d85-38aea88b68cf.png)

**Comment by TelepathicGrunt** [comment]
This is the code that adds my ocean dungeons. It only adds to biomes in the ocean category. 
https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/blob/f522a4b8904c6c0d397774ccd05cca94e1064ac3/src/main/java/com/telepathicgrunt/repurposedstructures/RSAddFeaturesAndStructures.java#L270

Just to make sure, click F3 and stand in the center. It does say Lush Desert right? If so, I’ll check terrestia to see if they put the desert in the wrong category or something

**Comment by TelepathicGrunt** [comment]
https://github.com/TerraformersMC/Terrestria/blob/3851310990e36a566ba64ac4e198d7666f1d3b19/src/main/java/com/terraformersmc/terrestria/biome/LushDesertBiomes.java#L21

Oh just looked. Yep it’s in the wrong category lol. I’ll contact them

**Comment by IdrisQe** [comment]
WELL that would explain it. That's just about as opposite as you can possibly get.
Are you making an Issue there, or should I?

**Comment by TelepathicGrunt** [comment]
I just talked to one of their devs on discord and they will fix it. I’ll keep this report open until their next update.

**Comment by TelepathicGrunt** [comment]
~~any day now they will release an update... lol~~
I'll keep this open until they release the fix.

**Comment by TelepathicGrunt** [comment]
v2.1.9 Repurposed Structures should now automatically put the ocean dungeons into the disallow biome list to remove them strictly from Terrestria's lush desert biome! Looks like terrestria isnt updating anymore rip
