### ISSUE TITLE
[Fabric 1.16.5] Latest update (v1.8.4) breaks WTHIT (WAILA-esque mod)

### ISSUE THREAD

**Issue by Fogrits** [TelepathicGrunt/RepurposedStructures-Fabric#87]
[Crash Report](https://pastebin.com/MFYkCc6w)

**Comment by Fogrits** [comment]
Looks like log4j isn't being recognized or something

**Comment by TelepathicGrunt** [comment]
actually looks like the message format is null itself so I cant do an equals comparison on it. Try this jar and see if that fixes it. I added a null check
[repurposed_structures-1.16.5-1.8.5.zip](https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/files/6059035/repurposed_structures-1.16.5-1.8.5.zip)

**Comment by Fogrits** [comment]
Yes, it fixes the problem (I wasn't even being able to boot into the main menu)

**Comment by TelepathicGrunt** [comment]
Awesome, just released that patch! Thank you for reporting this! v1.8.5 should be approved shortly
