### ISSUE TITLE
[Suggestion] Ice Temples

### ISSUE THREAD

**Issue by HenryMaxler** [TelepathicGrunt/RepurposedStructures-Fabric#91]
Hello, I have a suggestion: Ice Temples.  As you can see here pewdiepie did a video with a joke thumbnail of the ice temple:

https://www.youtube.com/watch?v=2U8OHYXeC3I

Also there is a video of the ice temple from a Minecraft PE map in a video:

https://www.youtube.com/watch?v=gOMakfqQ7R4

As you can see, there is some interest in the fable of the ice temple.  Because it looks like the desert temple, I think it would fit into this mod.

Preferably the ice temples could spawn in Frozen Ocean and other ice covered biomes.  I appreciate the work you put into the mod, I think it's great.  This suggestion is mainly for the forge version that I use, but I saw where it says to put suggestions over here in the fabric version.

**Comment by RDKRACZ** [comment]
It’s...already added? #74

**Comment by HenryMaxler** [comment]
That one is a snowy temple, which is also good.  But, it does not fit very well in the ice biomes.

It is different than the other one, and I was looking for that ice temple and couldn't find it.  It seems like there should be both.

**Comment by TelepathicGrunt** [comment]
Yeah as you saw from my comment on that other ice pyramid post, I really do not like the icy pyramid designs in those videos lol. It just looks so bad. I could try taking another stab at a different set blocks and style to see if I can do a better looking icy pyramid but no promises! It may be a while before I get time to add new structures to repurposed structures

**Comment by HenryMaxler** [comment]
No problem.
By the way, how do you learn how to create structures in game?  It seems very difficult and there are not many mods that add structures

**Comment by TelepathicGrunt** [comment]
Lots of time and effort and I have been doing it since 1.15.2. Though more and more mods are starting to have structures since I made a structure tutorial mod for modders to check out https://github.com/TelepathicGrunt/StructureTutorialMod

**Comment by TelepathicGrunt** [comment]
icy pyramids added in v1.10.0!
![2021-04-03_17 05 52](https://user-images.githubusercontent.com/40846040/113525797-fb57f780-9584-11eb-9d12-f1946286a0e0.png)
