### ISSUE TITLE
No end portal

### ISSUE THREAD

**Issue by botred** [TelepathicGrunt/RepurposedStructures-Fabric#93]
When me and my friends find the stronghold we cant seem to find the end portal. The stronghold itself exists but the end portal doesn't exist. Even when I'm playing singleplayer and using commands.

**Comment by TelepathicGrunt** [comment]
Can you give me a copy of your world and coordinates to the stronghold? 

-

**Comment by TelepathicGrunt** [comment]
Portal room is spawning for me. Have you tried being in spectator mode with night vision to make absolutely sure there's no portal room? a copy of the world would help as I can check
![image](https://user-images.githubusercontent.com/40846040/111657778-24853380-87e2-11eb-80ee-0a9402a3eecb.png)

**Comment by botred** [comment]
Sorry, I found the End Portal. turns out my friend was having a hard time seeing it when we split off to other directions. Thanks for helping and sorry for the troubles.

**Comment by TelepathicGrunt** [comment]
Ah. well I’m glad you two found the portal room! I was worried I might had caused a weird bug that I couldn’t reproduce lol. Have fun!
