### ISSUE TITLE
[Suggestion] Add surface openings to minehsafts

### ISSUE THREAD

**Issue by Hyperbean18** [TelepathicGrunt/RepurposedStructures-Fabric#94]
Adding surface openings to mineshafts like in Yungs Better Mineshafts would help worldbuilding. It would also be quite useful in finding End Mineshafts and nether mineshafts as players don't really explore the areas where they generate. Of course, surface openings should be quite rare

**Comment by TelepathicGrunt** [comment]
Well, remember, Repurposed Structures just aims to add biome variants of existing vanilla structures. Not completely redesign them. That's out of scope for my mod and is better suited for other mods. Like Yung's Better Mineshafts you said lol. You can disable the Mineshafts from my mod and use their mineshafts instead. But thank you for the suggestion tho!
