### ISSUE TITLE
REPU is spamming spawners

### ISSUE THREAD

**Issue by Hyperbean18** [TelepathicGrunt/RepurposedStructures-Fabric#97]
I loaded a new world and found a TON of spawners in an area that couldn't have been larger than 16x16 chunks(My render distance). I noticed this before in a ocean but brushed it off as a coincidence. Spawner generation rates should probably be tweaked.

Images: https://imgur.com/a/3EonjQ9
Seed is in the first image

**Comment by TelepathicGrunt** [comment]
Check the config. You might had set the spawn rates of dungeons too high

**Comment by Hyperbean18** [comment]
I haven't messed with the configs, but here

My dungeons Configs:
```
[RSDungeonsConfig.attemptsPerChunk]
badlandsDungeonAttemptsPerChunk = 8
darkForestDungeonAttemptsPerChunk = 8
desertDungeonAttemptsPerChunk = 8
jungleDungeonAttemptsPerChunk = 8
mushroomDungeonAttemptsPerChunk = 8
snowDungeonAttemptsPerChunk = 8
swampDungeonAttemptsPerChunk = 8
endDungeonAttemptsPerChunk = 8
netherDungeonAttemptsPerChunk = 8
oceanDungeonAttemptsPerChunk = 5

```
My config file: https://paste.gg/p/anonymous/3d4fc8ee744e4b8d86bd41d73ce1088e

**Comment by TelepathicGrunt** [comment]
Repurposed Structures dungeons do have a slightly more lax condition for spawning than vanilla dungeons so they tend to spawn in more places more often (which is good imo as vanilla's dungeons are too rare with it's strict spawn conditions). But I am not seeing the dungeons spawning at the rate that you are seeing with the triple dungeon. The other pictures looks fine tbh. 

You can try turning down the dungeon rates to see if that helps. I am currently rewriting dungeons to use nbt files and part of that was a slight change to the conditions of how they spawn so they might be less common in next update. ~~or maybe accidentally more common lol~~. I can give you a test jar of the new nbt based dungeons for you to test to see if the rates look more normal

**Comment by Hyperbean18** [comment]
> I can give you a test jar

That sounds pretty good! Would love to try it out. I'll also mess around with the configs a bit and see how it turns out

**Comment by Hyperbean18** [comment]
Nevermind, I did some more testing and it seems that desert was just really rare. Thanks!
